#!/usr/bin/env bash
set -e
set -o pipefail

# TODO: make "deploy" the default for "deploy-go", at some point.

function help_usage() {
    echo "$0 [start|status|restart|stop|deploy|deploy-python|deploy-go]"
    echo "  deploy|deploy-python: stop services then play ansible playbook (with Python engines)"
    echo "  deploy-go: stop services then play ansible playbook (with Go engines)"
    exit 1
}

if [ "$(id -u)" -ne 0 ]; then
    echo "$0: must be run as root"
    exit 1
fi

while [ 1 ]; do
    case $1 in
        start|status|restart|stop)
            /opt/canopsis/bin/canopsis-systemd $1
            exit $?
            ;;
        deploy|deploy-python)
            $0 stop
            /opt/canopsis/deploy-ansible/install-self.sh deploy-python
            exit $?
            ;;
        deploy-go)
            $0 stop
            /opt/canopsis/deploy-ansible/install-self.sh deploy-go
            exit $?
            ;;
        *)
            help_usage
            ;;
    esac
    shift
done
