#!/usr/bin/env python
# -*- coding: utf-8 -*-
# --------------------------------
# Copyright (c) 2015 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------
from argparse import ArgumentParser

from canopsis.migration.manager import MigrationTool
from canopsis.version import CANOPSIS_VERSION_ARG, CANOPSIS_STACK_ARG, CANOPSIS_EDITION_ARG

if __name__ == '__main__':
    parser = ArgumentParser(description='Canopsis Migration Tool')
    parser.add_argument('--yes', dest='yes', action='store_true')
    parser.add_argument('--authorize-reinit',
                        dest='reinit', action='store_true')
    parser.add_argument(CANOPSIS_VERSION_ARG, required=False, default=None,
                        dest='canopsis_version')
    parser.add_argument(CANOPSIS_EDITION_ARG, required=False,
                        default="core", dest='canopsis_edition', choices=['cat', 'core'])
    parser.add_argument(CANOPSIS_STACK_ARG, required=False,
                        default="go", dest='canopsis_stack', choices=['go'])
    args = parser.parse_args()

    mgr = MigrationTool(canopsis_version=args.canopsis_version,
                        canopsis_stack=args.canopsis_stack,
                        canopsis_edition=args.canopsis_edition)
    mgr.fill(yes=args.yes, reinit_auth=args.reinit)
