#!/bin/sh
set -u

if [ -z "$1" ]; then
    echo "Usage: $0 start|status|restart|stop [pattern]"
    exit 1
fi

if [ -z "$2" ]; then
    pattern="canopsis*"
else
    pattern="$2"
fi

for i in $(systemctl list-units -a --type=service "$pattern" | sed -En 's/^.*(canopsis-.*\.service).*/\1/pg'); do
    systemctl $1 $i
done
