#!/usr/bin/env python
# -*- coding: utf-8 -*-

from canopsis.common.mongo_store import MongoStore
from canopsis.common.collection import MongoCollection

import unittest

class CpsDiagTest(unittest.TestCase):

    def test_mongo_connection(self):
        store = MongoStore.get_default()
        coll = MongoCollection(store.get_collection('cpsdiag__'))
        coll.remove()
        coll.insert({'_id': 'diag', 'success': True})
        r = list(coll.find({'_id': 'diag'}))

        self.assertEqual(len(r), 1)

        coll.remove()

def main():
    unittest.main()

if __name__ == '__main__':
    main()