#!/bin/bash
set -e
set -o pipefail
if [ "${1}" = "" ]; then
    echo "Usage: $0 <engine_module>-<engine_name>"
    echo "Example: $0 dynamic-alerts"
    exit 1
fi

engine_module=$(echo -n "${1}" | sed -r 's/([^-]+)-.+/\1/g')
engine_name=$(echo -n "${1}" | sed -r 's/[^-]+-(.+)/\1/g')

if [ "${engine_module}" = "" ]; then
    echo "Invalid module: ${engine_module}"
    exit 2
fi

if [ "${engine_name}" = "" ]; then
    echo "Invalid name: ${engine_name}"
    exit 3
fi

shift

$HOME/bin/engine-launcher -e canopsis.engines.${engine_module} -n ${engine_name} $@
exit $?
