#!/usr/bin/env bash
set -e
set -o pipefail
if [ "${1}" = "" ]; then
    echo "Usage: $0 <engine_module>-<engine_name> [engine.mod.path]"
    echo "Example: $0 dynamic-alerts"
    echo "Example: $0 snmp-snmp canopsis_cat.engines"
    exit 1
fi

engine_mod_path="canopsis.engines"
if [ ! "${2}" = "" ]; then
    engine_mod_path="${2}"
fi

engine_module=$(echo -n "${1}" | sed -r 's/([^-]+)-.+/\1/g')
engine_name=$(echo -n "${1}" | sed -r 's/[^-]+-([^0-9]+).*/\1/g')

worker_id="1"
engine_worker_id=$(echo -n ${1} | sed -r 's/([0-9]*)$/\1/g')
if [[ ! "${engine_worker_id}" = "" ]]; then
    worker_id="${engine_worker_id}"
fi

if [ "${engine_module}" = "" ]; then
    echo "Invalid module: ${engine_module}"
    exit 2
fi

if [ "${engine_name}" = "" ]; then
    echo "Invalid name: ${engine_name}"
    exit 3
fi

shift

$HOME/bin/engine-launcher \
    -e ${engine_mod_path}.${engine_module} \
    -n ${engine_name} \
    -w ${worker_id} \
    -l ${LOGLEVEL}
