#!/usr/bin/env python

# https://github.com/benoitc/gunicorn/issues/669

from gunicorn.app.base import Application

from canopsis.webcore.wsgi import get_default_app


class WebServerPy(Application):
    """
    Transparently replace the usual gunicorn command so we can
    package the Canopsis Web Server with PyInstaller.
    """

    def __init__(self, wsgi_getter):
        super(WebServerPy, self).__init__()
        self.wsgi_getter = wsgi_getter

    def init(self, parser, opts, args):
        return {}

    def load(self):
        return self.wsgi_getter()


if __name__ == "__main__":
    gunicorn_app = WebServerPy(get_default_app)
    gunicorn_app.run()
