#!/usr/bin/env python

# https://github.com/benoitc/gunicorn/issues/669

import gunicorn

from gunicorn.app.base import Application, Config
from gunicorn import glogging
from gunicorn.workers import ggevent

from canopsis.webcore.wsgi import get_default_app

class WebServerPy(Application):

    def __init__(self, app_func, options=None):
        self.options = options or {}
        self.app_func = app_func
        super(Application, self).__init__()

    def load_config(self):
        self.cfg = Config()

        for key, value in options.items():
            self.cfg.set(key, value)

    def load(self):
        self.app = self.app_func()
        return self.app

if __name__ == "__main__":
    options = {
        'bind': '127.0.0.1:8082',
        'workers': 2,
        'worker_class': 'gevent',
    }
    gunicorn_app = WebServerPy(get_default_app, options)
    gunicorn_app.run()
