#!/usr/bin/env python

# https://github.com/benoitc/gunicorn/issues/669

from gunicorn.app.base import Application, Config
import gunicorn
from gunicorn import glogging
from gunicorn.workers import sync

from canopsis.webcore.wsgi import app as wsgi_app

class GUnicornFlaskApplication(Application):
    def __init__(self, app):
        self.usage, self.callable, self.prog, self.app = None, None, None, app

    def run(self, **options):
        self.cfg = Config()
        [self.cfg.set(key, value) for key, value in options.items()]
        return Application.run(self)

    load = lambda self:self.app

if __name__ == "__main__":
    gunicorn_app = GUnicornFlaskApplication(wsgi_app)
    gunicorn_app.run(
        worker_class="gunicorn.workers.sync.SyncWorker",
    )
