#!/usr/bin/env python
# -*- coding: utf-8 -*-
#--------------------------------
# Copyright (c) 2014 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------


import time
import polib
import sys
from canopsis.old.storage import get_storage
from canopsis.old.account import Account

from os.path import expanduser, isfile

class i18n(object):

    def __init__(self):
        self.misc = get_storage(namespace='misc', account=Account(user="root", group="root")).get_backend()
        self.query = {'crecord_type': 'i18n', '_id': 'translations'}


    def extract(self):

        now_str = time.strftime("%Y-%m-%d %H:%M")

        po = polib.POFile()
        po.metadata = {
            'Project-Id-Version': '1.0',
            'Report-Msgid-Bugs-To': 'teamcanopsis@capensis.fr',
            'POT-Creation-Date': '2014-08-22 10:00+0100',
            'PO-Revision-Date': now_str + '+0100',
            'Last-Translator': 'teamcanopsis <teamcanopsis@capensis.fr>',
            'Language-Team': 'English <teamcanopsis@capensis.fr>',
            'MIME-Version': '1.0',
            'Content-Type': 'text/plain; charset=utf-8',
            'Content-Transfer-Encoding': '8bit',
        }


        #Update lang file with existing po file
        base_lang_path = expanduser('~/locale/en/lang.po')
        if isfile(base_lang_path):
            po_base = polib.pofile(base_lang_path)
            for entry in po:
                entry = polib.POEntry(
                    msgid=entry.msgid,
                    msgstr=entry.msgid
                )
                po.append(entry)

        #Getting new fields to translate from db
        translations = self.misc.find_one(self.query)
        for term in translations['todo']:

            entry = polib.POEntry(
                msgid=term,
                msgstr=term,
            )
            po.append(entry)


        po.save(expanduser('~/locale/todo.po'))


if __name__ == '__main__':
    if 'extract' in sys.argv:
        i18n().extract()
