#!/opt/canopsis/bin/python
# EASY-INSTALL-SCRIPT: 'canopsis.tools==0.1','webmodulemanager'
__requires__ = 'canopsis.tools==0.1'
import pkg_resources
pkg_resources.run_script('canopsis.tools==0.1', 'webmodulemanager')
