#!/bin/bash

# Register all web modules

webmodulemanager add core
webmodulemanager add uibase
webmodulemanager add monitoring
webmodulemanager add development
webmodulemanager add uiv1_themes
webmodulemanager add canopsis-backend-ui-connector
webmodulemanager add userpreferences
webmodulemanager add charts
