#!/bin/bash

SRCDIR=`$HOME/var/www/canopsis`
SCHEMADIR=`$HOME/etc/schema.d`
WEBMODULES=`webmodulemanager list | cut -d' ' -f3 | xargs`

for webmodule in $WEBMODULES
do
    echo " -- Copying schemas from: $webmodule"
    cp $SRCDIR/$webmodule/schemas/* $SCHEMADIR/ || exit 1
done
