- name: Download influxdb package
  get_url:
    url: "https://repositories.canopsis.net/pulp/repos/influxdb/Packages/i/influxdb-{{ influxdb_version }}-1.x86_64.rpm"
    dest: "/var/cache/yum/influxdb-{{ influxdb_version }}-1.x86_64.rpm"
    checksum: "sha256:e9fb41a40e882034fff212cedbd8f380148cf3c4fe46f235de7e885e07e3ebbc"
  become: yes

- name: Install Influxdb
  yum:
    name: "/var/cache/yum/influxdb-{{ influxdb_version }}-1.x86_64.rpm"
    state: present
    disable_gpg_check: yes

- name: Define Config
  template:
    src: influxdb.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Start Influxdb
