[RabbitMQ]

# If you need to set extra arguments specific to the server implementation of
# exchange, uncomments args in section [[RabbitMQ.exchanges]] and add the
# required values. For more information see the documentation of the used
# rabbitMQ library and the documentation of our version of RabbitMQ.

# If you need to set extra arguments specific to the server implementation of
# queue, uncomments args in section [[RabbitMQ.queues]] and add the
# required values. For more information see the documentation of the used
# rabbitMQ library and the documentation of our version of RabbitMQ.

# If you need to set extra arguments specific to the server implementation for
# queue binding, uncomments args in section [[RabbitMQ.queues.bind]] and add the
# required values. For more information see the documentation of the
# used rabbitMQ library and the documentation of our version of RabbitMQ.

[[RabbitMQ.exchanges]]
name = "canopsis"
kind = "topic"
durable = true
autoDelete = false
internal = false
noWait = false
# args =

[[RabbitMQ.exchanges]]
name = "canopsis.alerts"
kind = "topic"
durable = true
autoDelete = false
internal = false
noWait = false
# args =

[[RabbitMQ.exchanges]]
name = "canopsis.events"
kind = "topic"
durable = true
autoDelete = false
internal = false
noWait = false
# args =

[[RabbitMQ.exchanges]]
name = "canopsis.incidents"
kind = "topic"
durable = true
autoDelete = false
internal = false
noWait = false
# args =

[[RabbitMQ.queues]]
name = "Engine_action"
durable = true
autoDelete = false
exclusive = false
noWait = false
# args =

[[RabbitMQ.queues]]
name = "Engine_axe"
durable = true
autoDelete = false
exclusive = false
noWait = false
# args =
  [RabbitMQ.queues.bind]
  key = "Engine_axe"
  exchange = "amq.direct"
  noWait = false
  # args =

[[RabbitMQ.queues]]
name = "Engine_che"
durable = true
autoDelete = false
exclusive = false
noWait = false
# args =
  [RabbitMQ.queues.bind]
  key = "#"
  exchange = "canopsis.events"
  noWait = false
  # args =

[[RabbitMQ.queues]]
name = "Engine_heartbeat"
durable = true
autoDelete = false
exclusive = false
noWait = false
# args =
  [RabbitMQ.queues.bind]
  key = "#"
  exchange = "canopsis.events"
  noWait = false
  # args =

[[RabbitMQ.queues]]
name = "Engine_watcher"
durable = true
autoDelete = false
exclusive = false
noWait = false
# args =
  [RabbitMQ.queues.bind]
  key = "Engine_watcher"
  exchange = "amq.direct"
  noWait = false
  # args =
