NAME="ubik"

LOG="$LOG_PATH/$NAME.log"
rm -f $LOG &> /dev/null

function build(){
	true
}

function install(){
	# Keep original Ubik bin
	if [ -e $PREFIX/bin/ubik ]; then
		cp $PREFIX/bin/ubik $PREFIX/bin/ubik.ori
	fi

	easy_install_pylib $SRC_PATH/externals/Ubik.tgz
	easy_install_pylib $SRC_PATH/externals/Ubik-toolbelt.tgz

	if [ -e $PREFIX/bin/ubik.ori ]; then
		rm -Rf $PREFIX/bin/ubik &> /dev/null || true
		mv $PREFIX/bin/ubik.ori $PREFIX/bin/ubik
	fi
}
