NAME="db-conf"

function build(){
	true
}


function install(){
	echo " + Post install configurations ..."

    cd $SRC_PATH
    install_basic_source $NAME

    install_conf "mongodb.conf"
    install_conf "influxdb.conf"
}

function update(){
    echo " + Post install configurations ..."

    cd $SRC_PATH
    update_basic_source $NAME

    install_conf "mongodb.conf"
    install_conf "influxdb.conf"
}
