NAME="mongodb"

BASE="mongodb-linux-$ARCH-$VERSION"
LOG="$LOG_PATH/$BASE.log"
rm -f $LOG &> /dev/null


function build(){
	su - $HUSER -c "service mongodb stop"

	cd $SRC_PATH/externals

	if [ ! -e $BASE ]; then
		extract_archive "$BASE.tar.xz"
	fi
}

function install(){
	cd $SRC_PATH/externals/$BASE
	check_code $?

	cp -R bin/* $PREFIX/bin/
	check_code $?

	chown $HUSER:$HGROUP $PREFIX/bin/mongo*
	check_code $?

	install_init "mongodb"

}
