NAME="librabbitmq"

FCHECK="$PREFIX/lib/librabbitmq.so"

LOG="$LOG_PATH/$NAME.log"
rm -f $LOG &> /dev/null

function build(){
	cd $SRC_PATH/externals

	if [ ! -e $NAME ]; then
		extract_archive "$NAME.tgz"
	fi
	cd  $NAME

	echo "   + python setup.py build"
	python setup.py build 1>> $LOG 2>> $LOG
	check_code $? 'Impossible to build'
}

function install(){
	cd $SRC_PATH/externals/$NAME

	python setup.py install 1>> $LOG 2>> $LOG
	check_code $? 'Impossible to install'
}
