NAME="webcore"

function build(){
	true
}

function install(){
	install_basic_source $NAME

	chown $HUSER $PREFIX/var/www/canopsis/resources/locales
	su - $HUSER -c "export http_proxy=$http_proxy && export https_proxy=$https_proxy && webcore_update_locales"
	if [ $? -ne 0 ] 
	then 
		echo "Impossible to download locales"
	fi

	echo "global.commit='$(git log | head -1 | cut -d ' ' -f2)'" > $PREFIX/var/www/canopsis/commit.js
}
