// Code generated by MockGen. DO NOT EDIT.
// Source: git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/correlation (interfaces: RulesAdapter)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/lib/canopsis/correlation/metaalarm.go git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/correlation RulesAdapter
//

// Package mock_correlation is a generated GoMock package.
package mock_correlation

import (
	context "context"
	reflect "reflect"

	correlation "git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/correlation"
	gomock "go.uber.org/mock/gomock"
)

// MockRulesAdapter is a mock of RulesAdapter interface.
type MockRulesAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockRulesAdapterMockRecorder
	isgomock struct{}
}

// MockRulesAdapterMockRecorder is the mock recorder for MockRulesAdapter.
type MockRulesAdapterMockRecorder struct {
	mock *MockRulesAdapter
}

// NewMockRulesAdapter creates a new mock instance.
func NewMockRulesAdapter(ctrl *gomock.Controller) *MockRulesAdapter {
	mock := &MockRulesAdapter{ctrl: ctrl}
	mock.recorder = &MockRulesAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRulesAdapter) EXPECT() *MockRulesAdapterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRulesAdapter) Get(ctx context.Context) ([]correlation.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]correlation.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRulesAdapterMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRulesAdapter)(nil).Get), ctx)
}

// GetRule mocks base method.
func (m *MockRulesAdapter) GetRule(ctx context.Context, id string) (correlation.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(correlation.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockRulesAdapterMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockRulesAdapter)(nil).GetRule), ctx, id)
}

// Save mocks base method.
func (m *MockRulesAdapter) Save(ctx context.Context, r correlation.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRulesAdapterMockRecorder) Save(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRulesAdapter)(nil).Save), ctx, r)
}
