db.runCommand({collMod: "user", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "role", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "eventfilter", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "view_playlist", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "action_scenario", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "meta_alarm_rules", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "dynamic_infos", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "entity_category", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "pbehavior_type", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "pbehavior_reason", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "pbehavior_exception", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "pbehavior", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "job_config", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "job", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "state_settings", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "broadcast_message", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "idle_rule", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "views", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "viewtabs", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "widgets", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "widget_filters", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "widget_templates", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "viewgroups", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "resolve_rule", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "flapping_rule", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "kpi_filter", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "pattern", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "map", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "default_snmprules", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "declare_ticket_rule", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "link_rule", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "alarm_tag", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "color_theme", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "icon", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "instruction", changeStreamPreAndPostImages: {enabled: false}})
db.runCommand({collMod: "default_entities", changeStreamPreAndPostImages: {enabled: false}})

db.instruction.updateMany({}, {
    $rename: {
        updated: "last_modified",
    }
});
