version: '2'
volumes:
  mongodbdata:
    driver: local
  influxdbdata:
      driver: local
  rabbitmqdata:
    driver: local
  exchangedata:
services:
  rabbitmq:
    image: canopsis/canopsis-rabbitmq-server:${RABBIT_TAG}
    ports:
      - 5673:5672
      - 25672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 2g
    oom_score_adj: -1000
  mongodb:
    image: mongo:3.6-jessie
    env_file: compose.mongo.env
    ports:
      - "37027:27017"
    volumes:
      - mongodbdata:/data/db
      - "./docker/mongo/:/docker-entrypoint-initdb.d"
    restart: unless-stopped
    mem_limit: 3g
    mem_reservation: 3g
    oom_score_adj: -1000
    command: '--wiredTigerCacheSizeGB 2560'
  influxdb:
    image: influxdb:1.5-alpine
    environment:
      - INFLUXDB_DB=canopsis
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=cpsinflux
      - INFLUXDB_PASSWORD=canopsis
      - INFLUXDB_WRITE_USER=cpsinflux
      - INFLUXDB_WRITE_USER_PASSWORD=canopsis
    ports:
      - 28086:8086
      - 24444:4444/udp
    volumes:
      - influxdbdata:/var/lib/influxdb
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 1g
    oom_score_adj: -1000
  redis:
    image: redis:4.0
    ports:
      - "26379:6379"
    restart: unless-stopped
