version: '2'
volumes:
  mongodbdata:
    driver: local
  influxdbdata:
      driver: local
  rabbitmqdata:
    driver: local
  importctxdata:
    driver: local
  dumpdata:
    driver: local
  exchangedata:
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=cpsrabbit
      - RABBITMQ_DEFAULT_PASS=canopsis
      - RABBITMQ_DEFAULT_VHOST=canopsis
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 2g
    oom_score_adj: -1000
  mongodb:
    image: mongo:3.6-jessie
    env_file: compose.mongo.env
    ports:
      - "27027:27017"
    volumes:
      - mongodbdata:/data/db
      - dumpdata:/dump/dumpdata
      - "./docker/mongo/:/docker-entrypoint-initdb.d"
    restart: unless-stopped
    mem_limit: 3g
    mem_reservation: 3g
    oom_score_adj: -1000
    command: '--wiredTigerCacheSizeGB 2560'
  influxdb:
    image: influxdb:1.5-alpine
    environment:
      - INFLUXDB_DB=canopsis
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=cpsinflux
      - INFLUXDB_PASSWORD=canopsis
      - INFLUXDB_WRITE_USER=cpsinflux
      - INFLUXDB_WRITE_USER_PASSWORD=canopsis
    ports:
      - 28086:8086
      - 24444:4444/udp
    volumes:
      - influxdbdata:/var/lib/influxdb
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 1g
    oom_score_adj: -1000
  redis:
    image: redis:4.0
    restart: unless-stopped
    ports:
      - 6379:6379
  init:
    image: canopsis/init:${CANOPSIS_TAG}
    depends_on:
      - "rabbitmq"
      - "mongodb"
    env_file:
      - compose.env
  provisionning:
    image: canopsis/canopsis-cat-prov:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    restart: "no"
    mem_limit: 200m
    mem_reservation: 200m
  event_filter:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=event_filter
      - ENGINE_MODULE=canopsis.engines.event_filter
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  pbehavior:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=pbehavior
      - ENGINE_MODULE=canopsis.engines.dynamic
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  context-graph:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=context-graph
      - ENGINE_MODULE=canopsis.engines.dynamic
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 2g
  scheduler:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=scheduler
      - ENGINE_MODULE=canopsis.engines.scheduler
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  task_mail:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=task_mail
      - ENGINE_MODULE=canopsis.engines.task_mail
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  task_importctx:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=task_importctx
      - ENGINE_MODULE=canopsis.engines.task_importctx
    volumes:
      - importctxdata:/opt/canopsis/tmp
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  webserver:
    image: canopsis/${ENGINE_IMAGE}:${CANOPSIS_TAG}
    env_file:
      - compose.env
    environment:
      - CPS_WEBSERVER=1
    depends_on:
      - "mongodb"
    ports:
      - "28082:8082"
    volumes:
      - importctxdata:/opt/canopsis/tmp
      - dumpdata:/opt/canopsis/var/www/src/canopsis/dumpdata
      - "./exchange:/opt/canopsis/data"
    links:
      - mongodb
      - rabbitmq
      - influxdb
    restart: always
    mem_limit: 1g
    mem_reservation: 1g
  action:
    image: canopsis/engine-action:${CANOPSIS_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
  axe:
    image: canopsis/engine-axe:${CANOPSIS_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
  che:
    image: canopsis/engine-che:${CANOPSIS_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
  heartbeat:
    image: canopsis/engine-heartbeat:${CANOPSIS_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
  watcher:
    image: canopsis/engine-watcher:${CANOPSIS_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
