stages:
  - build
  - test
  - packaging
  - publish

build_docker:
  stage: build
  tags: ["canopsis"]
  script: make docker_images NEXT_TAG=develop

  before_script:
    - uname -a
    - docker -v
    - git --no-pager show

test-unit:
  stage: test
  tags: ["canopsis"]
  script: echo "TODO unit tests"

  after_script:
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
    - docker volume prune -f

test-functionnal:
  stage: test
  tags: ["canopsis"]
  script: echo "TODO functionnal tests"

  after_script:
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
    - docker volume prune -f

build_package:
  stage: packaging
  tags: ["canopsis"]
  script: make package TAG=todo

publish-docker:
  stage: publish
  tags: ["canopsis"]
  script: echo "TODO push docker"

publish-:
  stage: publish
  tags: ["canopsis"]
  script: echo "TODO push packages"
