stages:
  - build
  - test
  - deploy

before_script:
  - uname -a
  - docker -v
  - git --no-pager show

build_images:
  stage: build
  tags: ["canopsis,docker"]
  script:
    - git submodule update --init
    - ./build-docker.sh ci develop

test:
  stage: test
  tags: ["canopsis,docker"]
  script:
    - export COMPOSE_HTTP_TIMEOUT=180
    - git submodule update --init
    - ./build-docker.sh ci develop test
    - echo CANOPSIS_TAG=ci-test >> .env
    - docker-compose -p test${CI_JOB_ID} up -d
    - docker exec -t test${CI_JOB_ID}_webserver_1 /bin/bash -c "/opt/canopsis/bin/schema2db"
    - docker exec -t test${CI_JOB_ID}_webserver_1 /bin/bash -c "yes | /opt/canopsis/bin/canopsis-filldb --update"
    - docker-compose -p test${CI_JOB_ID} restart
    - docker exec -t test${CI_JOB_ID}_webserver_1 /bin/bash -c "source ~/.bashrc && /opt/canopsis/bin/ut_runner /opt/canopsis/test"
    - docker cp test${CI_JOB_ID}_webserver_1:/opt/canopsis/tmp/tests_report/ tests_report

  artifacts:
    paths:
      - unit_tests

after_script:
  - docker-compose -p test-${CI_JOB_ID} down
