stages:
  - prebuild
  - build
  - test
  - packaging
  - publish

prebuild:
  stage: prebuild
  tags: ["canopsis"]
  only:
    - feat-simpler_build
  script:
    - uname -a
    - docker -v
    - git --no-pager show

build_docker_debian9:
  stage: build
  tags: ["canopsis"]
  only:
    - feat-simpler_build
  before_script:

  script:
    - make docker_images DISTRIBUTIONS=debian9

  after_script: 
    - make clean_images DISTRIBUTIONS=debian9

#publish:
#  stage: publish
#  tags: ["canopsis"]
#
#  before_script:
#    - echo "publish ..."
#    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" git.canopsis.net
#
#  script:
#    - make docker_push DISTRIBUTIONS=debian9
#
#  after_script:
#    - make clean_images DISTRIBUTIONS=debian9
