stages:
  - prebuild
  - build
  - test
  - packaging
  - publish

prebuild:
  stage: prebuild
  tags: ["canopsis"]
  only:
    - ci/new_ci
  script:
    - uname -a
    - docker -v
    - git --no-pager show

#build_docker_debian8:
#  stage: build
#  tags: ["canopsis"]
#
#  before_script:
#
#  script: make docker_images DISTRIBUTIONS=debian8
#
#  after_script:

build_docker_debian9:
  stage: build
  tags: ["canopsis"]
  only:
    - ci/new_ci
  before_script:

  script:
    - make docker_images DISTRIBUTIONS=debian9

  after_script: 
    - make clean_images DISTRIBUTIONS=debian9

#build_docker_centos7:
#  stage: build
#  tags: ["canopsis"]
#
#  before_script:
#
#  script: make docker_images DISTRIBUTIONS=centos7
#
#  after_script:
