stages:
  - test

before_script:
  - uname -a
  - docker -v
  - git --no-pager show

variables:
  COMPOSE_HTTP_TIMEOUT: "180"
  COMPOSE_PROJECT_NAME: "test${CI_JOB_ID}"
  CANOPSIS_DISTRIBUTION: "debian-9"
  CANOPSIS_TAG: "ci"
  CANOPSIS_DOCKER_MODE: "test-ci"

stage_test:
  stage: test
  tags: ["canopsis"]
  script:
    - docker build -t canopsis/uiv3:develop -f docker/Dockerfile .

  artifacts:
    paths:
      - tests_report

after_script:
  - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
  - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
  - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down

