stages:
  - test

before_script:
  - uname -a
  - docker -v
  - git --no-pager show

variables:
  COMPOSE_HTTP_TIMEOUT: "180"
  COMPOSE_PROJECT_NAME: "test${CI_JOB_ID}"
  CANOPSIS_DISTRIBUTION: "debian-9"
  CANOPSIS_TAG: "ci"
  CANOPSIS_UIV2_BRICKS_TAG: "develop"
  CANOPSIS_DOCKER_MODE: "test-ci"
  CANOPSIS_CATAG_TOKEN: "not_using_it"
  CANOPSIS_ENV_CONFIRM: "0"
  CANOPSIS_SKIP_GO: "1"
  CANOPSIS_BUILD_NEXT: "0"

stage_test:
  stage: test
  tags: ["canopsis"]
  script:
    - set
    - ./ci-gitlab.sh

  artifacts:
    paths:
      - tests_report

build_next:
   stage: test
   tags: ["canopsis"]
   script:
     - docker build -t canopsis/uiv3:develop -f docker/Dockerfile.canopsis-next-develop .
     - docker-compose -f docker-compose_next.yml -p ${COMPOSE_PROJECT_NAME}-next up -d
     - docker push canopsis/uiv3:develop
   only:
    changes:
      - sources/webcore/src/canopsis-next/**/*
    refs:
      - develop
   after_script:
     - docker-compose -f docker-compose_next.yml -p ${COMPOSE_PROJECT_NAME}-next kill
     - sleep 10
     - docker-compose -f docker-compose_next.yml -p ${COMPOSE_PROJECT_NAME}-next rm -sf
     - docker-compose -f docker-compose_next.yml -p ${COMPOSE_PROJECT_NAME}-next down

after_script:
  - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
  - sleep 10
  - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
  - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
  - docker volume prune -f
