stages:
  - build
  - test
  - packaging
  - publish

build_docker:
  stage: build
  tags: ["canopsis"]
  variables:
    NEXT_DIR: ./sources/webcore/src/canopsis-next
    NEXT_TAG: develop

  before_script:
    - uname -a
    - docker -v
    - git --no-pager show
    - rm -rf $NEXT_DIR
    - git clone https://git.canopsis.net/canopsis/canopsis-next.git -b $NEXT_TAG $NEXT_DIR

  script: make docker_images

  after_script:
    - rm -rf $NEXT_DIR

test-unit:
  stage: test
  tags: ["canopsis"]
  script: echo "TODO unit tests"

  after_script:
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
    - docker volume prune -f

test-functionnal:
  stage: test
  tags: ["canopsis"]
  script: echo "TODO functionnal tests"

  after_script:
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
    - docker volume prune -f

build_package-debian8:
  stage: packaging
  tags: ["canopsis"]

  variable:
    DISTRIBUTION: debian8
  script:
    - make docker DISTRIBUTIONS=$DISTRIBUTION
    - make packages DISTRIBUTIONS=$DISTRIBUTION

build_package-debian8:
  stage: packaging
  tags: ["canopsis"]

  variable:
    DISTRIBUTION: debian9
  script:
    - make docker DISTRIBUTIONS=$DISTRIBUTION
    - make packages DISTRIBUTIONS=$DISTRIBUTION

build_package-centos7:
  stage: packaging
  tags: ["canopsis"]

  variable:
    DISTRIBUTION: debian8
  script:
    - make docker DISTRIBUTIONS=$DISTRIBUTION
    - make packages DISTRIBUTIONS=$DISTRIBUTION

publish-docker:
  stage: publish
  tags: ["canopsis"]
  script: echo "TODO push docker"

publish-packages:
  stage: publish
  tags: ["canopsis"]
  script: echo "TODO push packages"
