stages:
  - prebuild
  - build
  - test
  - packaging
  - publish
  - doc
  - clean

prebuild:
  stage: prebuild
  tags: ["canopsis"]
  only:
    - feat-simpler_build
  script:
    - uname -a
    - docker -v
    - git --no-pager show

build_docker_debian8:
  stage: build
  tags: ["canopsis"]
  only:
    - feat-simpler_build
  before_script:

  script:
    - make docker_images DISTRIBUTIONS=debian9

  after_script:
    - make clean_images DISTRIBUTIONS=debian9

build_docker_debian9:
  stage: build
  tags: ["canopsis"]
  only:
    - feat-simpler_build
  before_script:

  script:
    - make docker_images DISTRIBUTIONS=debian9

  after_script: 
    - make clean_images DISTRIBUTIONS=debian9

build_docker_centos7:
  stage: build
  tags: ["canopsis"]
  only:
    - feat-simpler_build
  before_script:

  script:
    - make docker_images DISTRIBUTIONS=centos7

  after_script:
    - make clean_images DISTRIBUTIONS=centos7

test-unit:
  stage: test
  tags: ["canopsis"]
  script: echo "TODO unit tests"

  after_script:
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
    - docker volume prune -f

test-functionnal:
  stage: test
  tags: ["canopsis"]
  script: echo "TODO functionnal tests"

  after_script:
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} kill
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} rm -sf
    - docker-compose -f docker-compose.ci.yml -p ${COMPOSE_PROJECT_NAME} down
    - docker volume prune -f

#publish:
#  stage: publish
#  tags: ["canopsis"]
#
#  before_script:
#    - echo "publish ..."
#    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" git.canopsis.net
#
#  script:
#    - make docker_push DISTRIBUTIONS=debian9
#
#  after_script:
#    - make clean_images DISTRIBUTIONS=debian9

doc:
  stage: doc
  tags: ["canopsis"]
  script:
    - echo "build and publish doc."

clean:
  stage: clean
  only:
    - feat-simpler_build

  script:
    - make clean_images

