ARG CANOPSIS_TAG
ARG CANOPSIS_DISTRIBUTION

# FROM canopsis/canopsis-core:${CANOPSIS_DISTRIBUTION}-${CANOPSIS_TAG}
FROM canopsis/canopsis-core:develop
# COPY docker/files/entrypoint-prov-sync.sh /
ADD docker/files/entrypoint-prov.sh /
COPY sources/db-conf/ /opt/canopsis/

ENTRYPOINT /entrypoint-prov.sh
