site_name: Documentation Canopsis
site_url: https://doc.canopsis.net

repo_url: https://git.canopsis.net/canopsis/canopsis

docs_dir: 
   sources/docs/fr
copyright: Documentation © Capensis 2018–2020 / CC BY-SA 3.0 FR (https://creativecommons.org/licenses/by-sa/3.0/fr/)

theme:
  name: material
  language: fr
  logo: 'img/canopsis-mkdocs.png'
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true

extra:
  search:
    language: 'en'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: True

plugins:
    - search
