site_name: Canopsis Doc
site_url: https://doc.canopsis.net

repo_url: https://git.canopsis.net/canopsis/canopsis

docs_dir: sources/docs/fr
copyright: Documentation © Canopsis 2018 / CC BY-SA 3.0 FR (https://creativecommons.org/licenses/by-sa/3.0/fr/)

theme:
  name: material
  language: fr
  extra:
    search:
        language: 'fr, en'
  logo: 'img/canopsis-mkdocs.png'
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true


markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: True

plugins:
    - search

