export const alarms = [{
  d: 'Engine_alerts/f48fe52e047a',
  links: { consignes: [] },
  entity: {
    impact: ['f48fe52e047a', 'asd', 'gfdg', 'RRR'],
    name: 'Engine_alerts',
    enable_history: [1551713029],
    last_state_change: 1551852960,
    measurements: {},
    enabled: true,
    links: {},
    depends: ['Engine/engine'],
    infos: {},
    _id: 'Engine_alerts/f48fe52e047a',
    type: 'resource',
  },
  pbehaviors: [],
  t: 1551772591,
  v: {
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '0.65 evt/sec, 1.56897 sec/evt',
      t: 1551772591,
      val: 1,
    },
    extra: {},
    initial_long_output: null,
    creation_date: 1551852960,
    canceled: null,
    current_state_duration: 80429,
    duration: 60,
    display_name: 'KW-LB-XA',
    connector: 'Engine',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '0.65 evt/sec, 1.56897 sec/evt',
      t: 1551772591,
      val: 2,
    },
    last_event_date: 1551852960,
    resolved: null,
    tags: [],
    component: 'f48fe52e047a',
    last_update_date: 1551852960,
    snooze: null,
    ticket: null,
    resource: 'Engine_alerts',
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '0.65 evt/sec, 1.56897 sec/evt',
    output: '0.65 evt/sec, 1.56897 sec/evt',
    hard_limit: null,
  },
  infos: {},
  _id: '50378c8a-3fd7-11e9-9a16-0242ac16000a',
}, {
  d: 'CUSTOM - SILLAGE - CADRE P',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'SILLAGE - CADRE P',
    enable_history: [1526401514, 1526401514],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_sillage_p/scenario'],
    state: 3,
    last_state_change: 1551766721,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      product_line: {
        description: 'Ligne de produits',
        value: 'Fonctions d\'Appui',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
      parent_application_identifier: {
        description: 'Identifiant Application parente',
        value: 'CUSTOM - SILLAGE - CADRE P',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'CUSTOM - SILLAGE - CADRE P',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      parent_application_name: {
        description: 'Nom application parente',
        value: 'SILLAGE - CADRE P',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'P',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'True',
      },
      application_name: {
        description: 'Nom Application',
        value: 'SILLAGE - CADRE P',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
    },
    _id: 'CUSTOM - SILLAGE - CADRE P',
    mfilter: '{"infos.scenario_parent_app_name.value": "CUSTOM - SILLAGE - CADRE P"}',
  },
  pbehaviors: [{
    connector: 'canopsis',
    name: 'Maintenance - Cadre en cours de construction',
    author: 'root',
    enabled: true,
    reason: 'Autre',
    comments: null,
    filter: '{"_id": {"$in": ["CUSTOM - Rendez-vous Agences (cadre P)", "CUSTOM - SILLAGE - CADRE P"]}}',
    type_: 'Maintenance',
    connector_name: 'canopsis',
    rrule: null,
    tstart: 1527674157,
    tstop: 1528073704,
    _id: '8dc4a584-63ef-11e8-9dfa-0242ac12001a',
    eids: ['CUSTOM - Rendez-vous Agences (cadre P)', 'CUSTOM - SILLAGE - CADRE P'],
  }],
  t: 1551762309,
  v: {
    resolved: null,
    extra: {},
    initial_long_output: null,
    creation_date: 1551766721,
    canceled: null,
    current_state_duration: 90711,
    duration: 86299,
    display_name: 'RS-GL-VR',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '0 ok, 0 minor, 0 major, 1 critical',
      t: 1551762309,
      val: 3,
    },
    last_event_date: 1551852651,
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '0 ok, 0 minor, 0 major, 1 critical',
      t: 1551762309,
      val: 1,
    },
    tags: [],
    component: 'CUSTOM - SILLAGE - CADRE P',
    last_update_date: 1551766721,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '0 ok, 0 minor, 0 major, 1 critical',
    output: '0 ok, 0 minor, 0 major, 1 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    product_line: {
      description: 'Ligne de produits',
      value: 'Fonctions d\'Appui',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
    parent_application_identifier: {
      description: 'Identifiant Application parente',
      value: 'CUSTOM - SILLAGE - CADRE P',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'CUSTOM - SILLAGE - CADRE P',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    parent_application_name: {
      description: 'Nom application parente',
      value: 'SILLAGE - CADRE P',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'P',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'True',
    },
    application_name: {
      description: 'Nom Application',
      value: 'SILLAGE - CADRE P',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
  },
  _id: '85c6a972-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'DC2207CA4B2A0DF2',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'Dune Entreprises - cadre R',
    enable_history: [1528796632, 1528796632],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_dune_e54_pmsmp_r/scenario'],
    state: 2,
    last_state_change: 1551766724,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: ' ',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '0',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
      parent_application_identifier: {
        description: 'Identifiant Application parente',
        value: '55A969E64910068B',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      parent_application_name: {
        description: 'Nom application parente',
        value: 'DUNE::DUNE Entreprises',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'R',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'DC2207CA4B2A0DF2',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'True',
      },
      application_name: {
        description: 'Nom Application',
        value: 'Dune Entreprises - cadre R',
      },
      product_line: {
        description: 'Ligne de produits',
        value: '',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'True',
      },
    },
    _id: 'DC2207CA4B2A0DF2',
    mfilter: '{"infos.scenario_parent_app_name.value": "DC2207CA4B2A0DF2"}',
  },
  pbehaviors: [],
  t: 1551762309,
  v: {
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '0 ok, 0 minor, 1 major, 0 critical',
      t: 1551762309,
      val: 1,
    },
    extra: {},
    initial_long_output: null,
    creation_date: 1551766724,
    canceled: null,
    current_state_duration: 90711,
    duration: 86296,
    display_name: 'IM-VA-YX',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '0 ok, 0 minor, 1 major, 0 critical',
      t: 1551762309,
      val: 2,
    },
    last_event_date: 1551852653,
    resolved: null,
    tags: [],
    component: 'DC2207CA4B2A0DF2',
    last_update_date: 1551766724,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '0 ok, 0 minor, 1 major, 0 critical',
    output: '0 ok, 0 minor, 1 major, 0 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: ' ',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '0',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
    parent_application_identifier: {
      description: 'Identifiant Application parente',
      value: '55A969E64910068B',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    parent_application_name: {
      description: 'Nom application parente',
      value: 'DUNE::DUNE Entreprises',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'R',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'DC2207CA4B2A0DF2',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'True',
    },
    application_name: {
      description: 'Nom Application',
      value: 'Dune Entreprises - cadre R',
    },
    product_line: {
      description: 'Ligne de produits',
      value: '',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'True',
    },
  },
  _id: '876fbb2e-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'A9D3095E5189226F',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'AUDE Indemnisation - cadre R',
    enable_history: [1528796635, 1528796635],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_aude_indemn_r45/scenario', 'Sc_aude_indemn_r/scenario', 'Sc_aude_metn_r/scenario', 'Sc_aude_indemn_r97/scenario'],
    state: 3,
    last_state_change: 1551766704,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
      parent_application_identifier: {
        description: 'Identifiant Application parente',
        value: 'AFD2C869460B008E',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      parent_application_name: {
        description: 'Nom application parente',
        value: 'AUDE Indemnisation',
      },
      application_name: {
        description: 'Nom Application',
        value: 'AUDE Indemnisation - cadre R',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'R',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'A9D3095E5189226F',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'True',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      product_line: {
        description: 'Ligne de produits',
        value: '',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
    },
    _id: 'A9D3095E5189226F',
    mfilter: '{"infos.scenario_parent_app_name.value": "A9D3095E5189226F"}',
  },
  pbehaviors: [{
    connector: 'canopsis',
    name: 'Application en maintenance',
    author: 'root',
    enabled: true,
    reason: 'Autre',
    comments: null,
    filter: '{"_id": {"$in": ["A9D3095E5189226F", "PE.FR Espace Recruteur - Cadre VA"]}}',
    type_: 'Maintenance',
    connector_name: 'canopsis',
    rrule: null,
    tstart: 1527674696,
    tstop: 1528070641,
    _id: 'd07cfc54-63f0-11e8-9dfa-0242ac12001a',
    eids: ['A9D3095E5189226F', 'PE.FR Espace Recruteur - Cadre VA'],
  }],
  t: 1551762308,
  v: {
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '2 ok, 0 minor, 0 major, 2 critical',
      t: 1551762308,
      val: 1,
    },
    extra: {},
    initial_long_output: null,
    creation_date: 1551766704,
    canceled: null,
    current_state_duration: 90712,
    duration: 86316,
    display_name: 'IE-JX-JO',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '2 ok, 0 minor, 0 major, 2 critical',
      t: 1551762308,
      val: 3,
    },
    last_event_date: 1551852631,
    resolved: null,
    tags: [],
    component: 'A9D3095E5189226F',
    last_update_date: 1551766704,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '2 ok, 0 minor, 0 major, 2 critical',
    output: '2 ok, 0 minor, 0 major, 2 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
    parent_application_identifier: {
      description: 'Identifiant Application parente',
      value: 'AFD2C869460B008E',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    parent_application_name: {
      description: 'Nom application parente',
      value: 'AUDE Indemnisation',
    },
    application_name: {
      description: 'Nom Application',
      value: 'AUDE Indemnisation - cadre R',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'R',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'A9D3095E5189226F',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'True',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    product_line: {
      description: 'Ligne de produits',
      value: '',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
  },
  _id: '7b3380ac-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'B0B9F6DD4DC709BD',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'Aude Formation - cadre P',
    enable_history: [1528796628, 1528796628],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_gspfo_aude_p/scenario', 'Sc_gspfo_gsp_p/scenario'],
    state: 3,
    last_state_change: 1551766705,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'INC0452204 - time out ',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
      parent_application_identifier: {
        description: 'Identifiant Application parente',
        value: 'B768BB584E54011F',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      parent_application_name: {
        description: 'Nom application parente',
        value: 'AUDE Formation',
      },
      application_name: {
        description: 'Nom Application',
        value: 'Aude Formation - cadre P',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'P',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'B0B9F6DD4DC709BD',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'False',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      product_line: {
        description: 'Ligne de produits',
        value: '',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'True',
      },
    },
    _id: 'B0B9F6DD4DC709BD',
    mfilter: '{"infos.scenario_parent_app_name.value": "B0B9F6DD4DC709BD"}',
  },
  pbehaviors: [],
  t: 1551762308,
  v: {
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '1 ok, 0 minor, 0 major, 1 critical',
      t: 1551762308,
      val: 1,
    },
    extra: {},
    initial_long_output: null,
    creation_date: 1551766705,
    canceled: null,
    current_state_duration: 90712,
    duration: 86315,
    display_name: 'NZ-DH-VM',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '1 ok, 0 minor, 0 major, 1 critical',
      t: 1551762308,
      val: 3,
    },
    last_event_date: 1551852634,
    resolved: null,
    tags: [],
    component: 'B0B9F6DD4DC709BD',
    last_update_date: 1551766705,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '1 ok, 0 minor, 0 major, 1 critical',
    output: '1 ok, 0 minor, 0 major, 1 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'INC0452204 - time out ',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
    parent_application_identifier: {
      description: 'Identifiant Application parente',
      value: 'B768BB584E54011F',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    parent_application_name: {
      description: 'Nom application parente',
      value: 'AUDE Formation',
    },
    application_name: {
      description: 'Nom Application',
      value: 'Aude Formation - cadre P',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'P',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'B0B9F6DD4DC709BD',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'False',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    product_line: {
      description: 'Ligne de produits',
      value: '',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'True',
    },
  },
  _id: '7c4f96a6-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'C03B077F51150D0F',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'AUDE Indemnisation - cadre P',
    enable_history: [1528796635, 1528796635],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_aude_metn_p/scenario', 'Sc_aude_indemn_p/scenario', 'Sc_aude_indemn_p25/scenario'],
    state: 3,
    last_state_change: 1551766707,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
      parent_application_identifier: {
        description: 'Identifiant Application parente',
        value: 'AFD2C869460B008E',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      parent_application_name: {
        description: 'Nom application parente',
        value: 'AUDE Indemnisation',
      },
      application_name: {
        description: 'Nom Application',
        value: 'AUDE Indemnisation - cadre P',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'P',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'C03B077F51150D0F',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'True',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      product_line: {
        description: 'Ligne de produits',
        value: '',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
    },
    _id: 'C03B077F51150D0F',
    mfilter: '{"infos.scenario_parent_app_name.value": "C03B077F51150D0F"}',
  },
  pbehaviors: [{
    connector: 'canopsis',
    name: 'Maintenance - Cadre en cours de construction',
    author: 'root',
    enabled: true,
    reason: 'Autre',
    comments: null,
    filter: '{"_id": {"$in": ["C03B077F51150D0F", "2E1730F14CC10021", "CUSTOM - ACTIVITES ET PILOTAGE - BPM - cadre t", "CUSTOM - DUNE OFFRES - CADRE D", "FF306DB74E4E13AD", "2F54A3DF4DAE3ABA", "CUSTOM - MAP - Mon Assistant Personnel - cadre t"]}}',
    type_: 'Maintenance',
    connector_name: 'canopsis',
    rrule: null,
    tstart: 1527674108,
    tstop: 1528073654,
    _id: '723c8b7e-63ef-11e8-9dfa-0242ac12001a',
    eids: ['2E1730F14CC10021', '2F54A3DF4DAE3ABA', 'C03B077F51150D0F', 'CUSTOM - ACTIVITES ET PILOTAGE - BPM - cadre t', 'CUSTOM - DUNE OFFRES - CADRE D', 'CUSTOM - MAP - Mon Assistant Personnel - cadre t', 'FF306DB74E4E13AD'],
  }],
  t: 1551762308,
  v: {
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '2 ok, 0 minor, 0 major, 1 critical',
      t: 1551762308,
      val: 1,
    },
    extra: {},
    initial_long_output: null,
    creation_date: 1551766707,
    canceled: null,
    current_state_duration: 90712,
    duration: 86313,
    display_name: 'HR-JE-VQ',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '2 ok, 0 minor, 0 major, 1 critical',
      t: 1551762308,
      val: 3,
    },
    last_event_date: 1551852640,
    resolved: null,
    tags: [],
    component: 'C03B077F51150D0F',
    last_update_date: 1551766707,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '2 ok, 0 minor, 0 major, 1 critical',
    output: '2 ok, 0 minor, 0 major, 1 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
    parent_application_identifier: {
      description: 'Identifiant Application parente',
      value: 'AFD2C869460B008E',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    parent_application_name: {
      description: 'Nom application parente',
      value: 'AUDE Indemnisation',
    },
    application_name: {
      description: 'Nom Application',
      value: 'AUDE Indemnisation - cadre P',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'P',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'C03B077F51150D0F',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'True',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    product_line: {
      description: 'Ligne de produits',
      value: '',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
  },
  _id: '7d72fc8a-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'CUSTOM - CAROE - CADRE P',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'CAROE - CADRE P',
    enable_history: [1528796639, 1528796639],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_caroe_p/scenario'],
    state: 3,
    last_state_change: 1551766713,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'P',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'CUSTOM - CAROE - CADRE P',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'False',
      },
      application_name: {
        description: 'Nom Application',
        value: 'CAROE - CADRE P',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
    },
    _id: 'CUSTOM - CAROE - CADRE P',
    mfilter: '{"infos.scenario_parent_app_name.value": "CUSTOM - CAROE - CADRE P"}',
  },
  pbehaviors: [],
  t: 1551762308,
  v: {
    resolved: null,
    extra: {},
    initial_long_output: null,
    creation_date: 1551766713,
    canceled: null,
    current_state_duration: 90712,
    duration: 86307,
    display_name: 'ZC-NJ-JB',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '0 ok, 0 minor, 0 major, 1 critical',
      t: 1551762308,
      val: 3,
    },
    last_event_date: 1551852644,
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '0 ok, 0 minor, 0 major, 1 critical',
      t: 1551762308,
      val: 1,
    },
    tags: [],
    component: 'CUSTOM - CAROE - CADRE P',
    last_update_date: 1551766713,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '0 ok, 0 minor, 0 major, 1 critical',
    output: '0 ok, 0 minor, 0 major, 1 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'P',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'CUSTOM - CAROE - CADRE P',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'False',
    },
    application_name: {
      description: 'Nom Application',
      value: 'CAROE - CADRE P',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
  },
  _id: '80f674ae-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'CUSTOM - DUDE - CADRE P',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'DUDE - CADRE P',
    enable_history: [1528796639, 1528796639],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_dude_p/scenario'],
    state: 2,
    last_state_change: 1551766715,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'P',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'CUSTOM - DUDE - CADRE P',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'False',
      },
      application_name: {
        description: 'Nom Application',
        value: 'DUDE - CADRE P',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
    },
    _id: 'CUSTOM - DUDE - CADRE P',
    mfilter: '{"infos.scenario_parent_app_name.value": "CUSTOM - DUDE - CADRE P"}',
  },
  pbehaviors: [],
  t: 1551762308,
  v: {
    resolved: null,
    extra: {},
    initial_long_output: null,
    creation_date: 1551766715,
    canceled: null,
    current_state_duration: 90712,
    duration: 86305,
    display_name: 'IY-CG-RV',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '0 ok, 0 minor, 1 major, 0 critical',
      t: 1551762308,
      val: 2,
    },
    last_event_date: 1551852646,
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '0 ok, 0 minor, 1 major, 0 critical',
      t: 1551762308,
      val: 1,
    },
    tags: [],
    component: 'CUSTOM - DUDE - CADRE P',
    last_update_date: 1551766715,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '0 ok, 0 minor, 1 major, 0 critical',
    output: '0 ok, 0 minor, 1 major, 0 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'P',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'CUSTOM - DUDE - CADRE P',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'False',
    },
    application_name: {
      description: 'Nom Application',
      value: 'DUDE - CADRE P',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
  },
  _id: '8226d4c2-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'CUSTOM - DUNE OFFRES - CADRE D',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'DUNE OFFRES - CADRE D',
    enable_history: [1528796639, 1528796639],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_dune_offres_d/scenario'],
    state: 2,
    last_state_change: 1551766717,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '1',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      application_crit_label: {
        description: 'Application criticity label',
        value: 'Critique',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'P',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'CUSTOM - DUNE OFFRES - CADRE D',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'False',
      },
      application_name: {
        description: 'Nom Application',
        value: 'DUNE OFFRES - CADRE D',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
    },
    _id: 'CUSTOM - DUNE OFFRES - CADRE D',
    mfilter: '{"infos.scenario_parent_app_name.value": "CUSTOM - DUNE OFFRES - CADRE D"}',
  },
  pbehaviors: [{
    connector: 'canopsis',
    name: 'Maintenance - Cadre en cours de construction',
    author: 'root',
    enabled: true,
    reason: 'Autre',
    comments: null,
    filter: '{"_id": {"$in": ["C03B077F51150D0F", "2E1730F14CC10021", "CUSTOM - ACTIVITES ET PILOTAGE - BPM - cadre t", "CUSTOM - DUNE OFFRES - CADRE D", "FF306DB74E4E13AD", "2F54A3DF4DAE3ABA", "CUSTOM - MAP - Mon Assistant Personnel - cadre t"]}}',
    type_: 'Maintenance',
    connector_name: 'canopsis',
    rrule: null,
    tstart: 1527674108,
    tstop: 1528073654,
    _id: '723c8b7e-63ef-11e8-9dfa-0242ac12001a',
    eids: ['2E1730F14CC10021', '2F54A3DF4DAE3ABA', 'C03B077F51150D0F', 'CUSTOM - ACTIVITES ET PILOTAGE - BPM - cadre t', 'CUSTOM - DUNE OFFRES - CADRE D', 'CUSTOM - MAP - Mon Assistant Personnel - cadre t', 'FF306DB74E4E13AD'],
  }],
  t: 1551762308,
  v: {
    resolved: null,
    extra: {},
    initial_long_output: null,
    creation_date: 1551766717,
    canceled: null,
    current_state_duration: 90712,
    duration: 86303,
    display_name: 'DA-YS-YA',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '0 ok, 0 minor, 1 major, 0 critical',
      t: 1551762308,
      val: 2,
    },
    last_event_date: 1551852648,
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '0 ok, 0 minor, 1 major, 0 critical',
      t: 1551762308,
      val: 1,
    },
    tags: [],
    component: 'CUSTOM - DUNE OFFRES - CADRE D',
    last_update_date: 1551766717,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '0 ok, 0 minor, 1 major, 0 critical',
    output: '0 ok, 0 minor, 1 major, 0 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '1',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    application_crit_label: {
      description: 'Application criticity label',
      value: 'Critique',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'P',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'CUSTOM - DUNE OFFRES - CADRE D',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'False',
    },
    application_name: {
      description: 'Nom Application',
      value: 'DUNE OFFRES - CADRE D',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
  },
  _id: '8357617c-3f0e-11e9-9a16-0242ac16000a',
}, {
  d: 'FF306DB74E4E13AD',
  links: { consignes: [] },
  entity: {
    impact: ['asd', 'gfdg', 'RRR', 'asdasd'],
    links: {},
    name: 'Dune Entreprises - cadre D',
    enable_history: [1528796632, 1528796632],
    type: 'watcher',
    measurements: {},
    enabled: true,
    depends: ['Sc_dune_e54_pmsmp_d/scenario', 'Sc_dune_e54_noheto_d/scenario', 'Sc_dune_e54_imt_d/scenario', 'Sc_dune_e54_etab_d/scenario', 'Sc_dune_e54_listoffr_d/scenario', 'Sc_dune_e54_pdaction_d/scenario'],
    state: 2,
    last_state_change: 1551766415,
    infos: {
      service_period: {
        description: 'Plage de service de l\'application',
        value: 'c5j_4h_18h15',
      },
      manual_maintenance_comment: {
        description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
        value: 'NullData',
      },
      display_on_weather: {
        description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
        value: 'True',
      },
      application_crit_code: {
        description: 'Criticit\u00e9 - Code',
        value: '0',
      },
      weather_type: {
        description: 'Type de m\u00e9t\u00e9o de service',
        value: 'MDSA',
      },
      manual_maintenance: {
        description: 'Indique si l\'app est actuellement en maintenance manuelle',
        value: 'False',
      },
      parent_application_identifier: {
        description: 'Identifiant Application parente',
        value: '55A969E64910068B',
      },
      pos: {
        description: 'POS',
        value: '',
      },
      display_on_tv: {
        description: 'Afficher ou non l\'application sur une TV',
        value: 'False',
      },
      resource_mds: {
        description: 'Lien avec le sc\u00e9nario',
        value: '',
      },
      parent_application_name: {
        description: 'Nom application parente',
        value: 'DUNE::DUNE Entreprises',
      },
      cadre: {
        description: 'Cadre (applications fabricant)',
        value: 'D',
      },
      application_identifier: {
        description: 'Identifiant Application',
        value: 'FF306DB74E4E13AD',
      },
      isInCarat: {
        description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
        value: 'True',
      },
      application_name: {
        description: 'Nom Application',
        value: 'Dune Entreprises - cadre D',
      },
      product_line: {
        description: 'Ligne de produits',
        value: '',
      },
      target_platform: {
        description: 'Environnement (production ou fabricant)',
        value: 'fabricant',
      },
    },
    _id: 'FF306DB74E4E13AD',
    mfilter: '{"infos.scenario_parent_app_name.value": "FF306DB74E4E13AD"}',
  },
  pbehaviors: [{
    connector: 'canopsis',
    name: 'Maintenance - Cadre en cours de construction',
    author: 'root',
    enabled: true,
    reason: 'Autre',
    comments: null,
    filter: '{"_id": {"$in": ["C03B077F51150D0F", "2E1730F14CC10021", "CUSTOM - ACTIVITES ET PILOTAGE - BPM - cadre t", "CUSTOM - DUNE OFFRES - CADRE D", "FF306DB74E4E13AD", "2F54A3DF4DAE3ABA", "CUSTOM - MAP - Mon Assistant Personnel - cadre t"]}}',
    type_: 'Maintenance',
    connector_name: 'canopsis',
    rrule: null,
    tstart: 1527674108,
    tstop: 1528073654,
    _id: '723c8b7e-63ef-11e8-9dfa-0242ac12001a',
    eids: ['2E1730F14CC10021', '2F54A3DF4DAE3ABA', 'C03B077F51150D0F', 'CUSTOM - ACTIVITES ET PILOTAGE - BPM - cadre t', 'CUSTOM - DUNE OFFRES - CADRE D', 'CUSTOM - MAP - Mon Assistant Personnel - cadre t', 'FF306DB74E4E13AD'],
  }],
  t: 1551762189,
  v: {
    status: {
      a: 'system',
      _t: 'statusinc',
      m: '2 ok, 0 minor, 4 major, 0 critical',
      t: 1551762189,
      val: 1,
    },
    extra: {},
    initial_long_output: null,
    creation_date: 1551766415,
    canceled: null,
    current_state_duration: 90831,
    duration: 86605,
    display_name: 'KE-AE-IR',
    connector: 'canopsis',
    state: {
      a: 'system',
      _t: 'stateinc',
      m: '2 ok, 0 minor, 4 major, 0 critical',
      t: 1551762189,
      val: 2,
    },
    last_event_date: 1551852982,
    resolved: null,
    tags: [],
    component: 'FF306DB74E4E13AD',
    last_update_date: 1551766415,
    snooze: null,
    ticket: null,
    resource: null,
    ack: null,
    long_output: null,
    long_out_history: [null],
    connector_name: 'engine',
    initial_output: '2 ok, 0 minor, 4 major, 0 critical',
    output: '2 ok, 0 minor, 4 major, 0 critical',
    hard_limit: null,
  },
  infos: {
    service_period: {
      description: 'Plage de service de l\'application',
      value: 'c5j_4h_18h15',
    },
    manual_maintenance_comment: {
      description: 'Commentaire ajout\u00e9 lors d\'une mise en maintenance manuelle',
      value: 'NullData',
    },
    display_on_weather: {
      description: 'Afficher ou non l\'application sur une m\u00e9t\u00e9o',
      value: 'True',
    },
    application_crit_code: {
      description: 'Criticit\u00e9 - Code',
      value: '0',
    },
    weather_type: {
      description: 'Type de m\u00e9t\u00e9o de service',
      value: 'MDSA',
    },
    manual_maintenance: {
      description: 'Indique si l\'app est actuellement en maintenance manuelle',
      value: 'False',
    },
    parent_application_identifier: {
      description: 'Identifiant Application parente',
      value: '55A969E64910068B',
    },
    pos: {
      description: 'POS',
      value: '',
    },
    display_on_tv: {
      description: 'Afficher ou non l\'application sur une TV',
      value: 'False',
    },
    resource_mds: {
      description: 'Lien avec le sc\u00e9nario',
      value: '',
    },
    parent_application_name: {
      description: 'Nom application parente',
      value: 'DUNE::DUNE Entreprises',
    },
    cadre: {
      description: 'Cadre (applications fabricant)',
      value: 'D',
    },
    application_identifier: {
      description: 'Identifiant Application',
      value: 'FF306DB74E4E13AD',
    },
    isInCarat: {
      description: 'Indique si l\'app a \u00e9t\u00e9 cr\u00e9\u00e9 automatiquement',
      value: 'True',
    },
    application_name: {
      description: 'Nom Application',
      value: 'Dune Entreprises - cadre D',
    },
    product_line: {
      description: 'Ligne de produits',
      value: '',
    },
    target_platform: {
      description: 'Environnement (production ou fabricant)',
      value: 'fabricant',
    },
  },
  _id: 'cf5e9c76-3f0d-11e9-9a16-0242ac16000a',
}];

export default {
  alarms,
};
