#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          canopsis
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Canopsis deamons
# Description:       Start Canopsis deamons
### END INIT INFO

NAME=canopsis
USER=@HUSER@

CANOPSIS_PATH="@PREFIX@"

case $1 in
	start)		
		echo "Starting $NAME:"
		su - $USER -c "$CANOPSIS_PATH/bin/hypcontrol start"
	;;
	
	stop)		
		echo "Stopping $NAME:"
		su - $USER -c "$CANOPSIS_PATH/bin/hypcontrol stop"
	;;
	
	restart)
		echo "Restarting $NAME:"	
		su - $USER -c "$CANOPSIS_PATH/bin/hypcontrol restart"
	;;
		
	status)
		echo "State of $NAME:"
		su - $USER -c "$CANOPSIS_PATH/bin/hypcontrol status"
	;;

	*)
	# For invalid arguments, print the usage message.
	echo "Usage: $0 {start|stop|restart|status}"
	exit 2
	;;
esac