CPS_MONGO_URL="mongodb://cpsmongo:canopsis@localhost:27017/canopsis"
CPS_INFLUX_URL="http://cpsinflux:canopsis@localhost:8086/canopsis"
CPS_AMQP_URL="amqp://cpsrabbit:canopsis@localhost:5672/canopsis"
CPS_REDIS_URL="redis://localhost:6379/0"
