<template>
  <svg
    width="45"
    height="45"
    viewBox="0 0 45 45"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="2"
      y="2"
      width="41"
      height="41"
      stroke="currentColor"
      stroke-dasharray="5 5"
    />
    <rect
      x="0"
      y="0"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="0"
      y="20.5"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="0"
      y="41"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="20.5"
      y="0"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="20.5"
      y="41"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="41"
      y="20.5"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="41"
      y="0"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <rect
      x="41"
      y="41"
      width="4"
      height="4"
      fill="white"
      stroke="currentColor"
    />
    <text
      x="6"
      y="26"
      fill="currentColor"
      font-size="14px"
    >Text</text>
  </svg>
</template>
