---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: ensure libselinux-python is installed
      yum:
        name: libselinux-python,selinux-policy
        state: present
      when: ansible_os_family == "RedHat"

    - name: Disable SELinux on RedHat familly
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"

- hosts: canopsis-standalone
  remote_user: root
  roles:
    -
      role: "canopsis"
      tags:
        - canopsis
