---
canopsis_home: /opt/canopsis
canopsis_user: canopsis
canopsis_group: canopsis

canopsis_oldapi_host: localhost
canopsis_oldapi_port: "8081"

canopsis_api_host: localhost
canopsis_api_port: "8082"

canopsis_amqp_host: localhost
canopsis_amqp_user: canopsis
canopsis_amqp_userid: cpsrabbit
canopsis_amqp_password: canopsis
canopsis_amqp_exchange: canopsis
canopsis_amqp_vhost: canopsis
canopsis_amqp_port: "5672"

canopsis_rabbit_nodename: rabbit@{{ ansible_hostname }}

canopsis_mongo_host: localhost
canopsis_mongo_db: canopsis
canopsis_mongo_user: cpsmongo
canopsis_mongo_password: canopsis
canopsis_mongo_port: "27017"

canopsis_postgresql_user: cpspostgres
canopsis_postgresql_password: password
canopsis_postgresql_host: localhost
canopsis_postgresql_port: "5432"
canopsis_postgresql_db: canopsis

canopsis_redis_host: localhost
canopsis_redis_port: "6379"
canopsis_redis_dbnum: 0

# 'community' or 'pro'
canopsis_edition: community

# snmp engine has no module name…
canopsis_pro_python_additional_engines_broken_names:
  -
    name: snmp

# Default Go engines for Community
canopsis_community_go_engines:
  -
    name: engine-action
  -
    name: engine-axe
  -
    name: engine-che
  -
    name: engine-fifo
  -
    name: engine-pbehavior
  -
    name: engine-service

# Additional Go engines for Canopsis Pro
canopsis_pro_go_additional_engines:
  -
    name: engine-correlation
  -
    name: engine-dynamic-infos
  -
    name: engine-remediation
  -
    name: engine-webhook

# Default other Core components
canopsis_community_other_default_services:
  -
    name: canopsis-api
  -
    name: canopsis-oldapi

# Other default Pro components
canopsis_pro_other_default_services:
  -
    name: connector-junit
