#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    echo "You must run this command as root ..."
    exit 1
fi

SRC=$(pwd)
CPS=$(cat $SRC/sources/canohome/lib/common.sh  | grep 'PREFIX' | cut -d'"' -f2)

source $SRC/tools/slink_utils

if [ ! -d .git ];
then
    echo ".git dir not found!"
    exit 1
fi

LINK=1
while test $# -gt 0; do
    case "$1" in
	-u)
	    shift
	    echo "Uninstalling symlinks ..."
	    LINK=0
	    ;;
	*)
	    shift
	    ;;
    esac
done

remove_slinks
if [ $LINK -eq 1 ]; then
    echo "Creating symlinks ..."
    create_slinks
fi
