---
- name: Create canopsis Vhost for RabbitMQ
  rabbitmq_vhost:
    name: "{{ canopsis_amqp_vhost }}"
    state: present
    node: "{{ canopsis_rabbit_nodename }}"

- name: Create canopsis user for RabbitMQ
  rabbitmq_user:
    user: "{{ canopsis_amqp_userid }}"
    node: "{{ canopsis_rabbit_nodename }}"
    password: "{{ canopsis_amqp_password }}"
    tags: administrator
    permissions:
      - vhost: "{{ canopsis_amqp_vhost }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Enable the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
