---
- name: Deploy Canopsis default configuration file for Nginx
  template:
    src: nginx/default.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  vars:
    # Note: requiring a local resolver to resolve localhost seems excessive, so just give 127.0.0.1
    # to Nginx in this case, which should be OK in most setups.
    CPS_API_URL: "http://{{ canopsis_api_host | replace('localhost', '127.0.0.1') }}:{{ canopsis_api_port }}"
    CPS_OLD_API_URL: "http://{{ canopsis_oldapi_host | replace('localhost', '127.0.0.1') }}:{{ canopsis_oldapi_port }}"
    CPS_SERVER_NAME: "localhost"

- name: Make sure that /etc/nginx/ssl is created with restricted permissions
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0750
    recurse: no

- name: Deploy Canopsis HTTPS configuration file for Nginx
  template:
    src: nginx/https.j2
    dest: /etc/nginx/https.inc
    owner: root
    group: root
    mode: 0644

- name: Deploy Canopsis CORS configuration file for Nginx
  template:
    src: nginx/cors.j2
    dest: /etc/nginx/cors.inc
    owner: root
    group: root
    mode: 0644

- name: Deploy Canopsis resolver configuration file for Nginx
  template:
    src: nginx/resolvers.j2
    dest: /etc/nginx/resolvers.inc
    owner: root
    group: root
    mode: 0644

- name: Deploy Rundeck configuration file for Nginx
  template:
    src: nginx/rundeck.j2
    dest: /etc/nginx/rundeck.inc
    owner: root
    group: root
    mode: 0644
  vars:
    # Note: requiring a local resolver to resolve localhost seems excessive, so just give 127.0.0.1
    # to Nginx in this case, which should be OK in most setups.
    RUNDECK_GRAILS_URL: "http://127.0.0.1/rundeck"
    # Note: this will do, as a default catch-all value, as long as we don't enable HTTPS by default.
    NGINX_URL: "http://nginx"
