---
- name: Create canopsis user for MongoDB
  mongodb_user:
    login_database: "admin"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ canopsis_mongo_port }}"
    login_host: "{{ canopsis_mongo_host }}"
    database: "{{ canopsis_mongo_db }}"
    name: "{{ canopsis_mongo_user }}"
    password: "{{ canopsis_mongo_password }}"
    state: present
    roles:
      - 'dbOwner'
