---
- name: Taking care of database migration
  command: "{{ canopsis_home }}/bin/canopsinit --canopsis-edition {{ canopsis_edition }}"
  register: canospinitcmd
  failed_when: canospinitcmd.rc != 0
  tags:
    - cps_canopsinit
