---
- name: Taking care of database migration
  # note: this legacy tool still expects cat/core values
  command: "{{ canopsis_home }}/bin/canopsinit --canopsis-edition {{ canopsis_edition | replace('community', 'core') | replace('pro', 'cat') }}"
  register: canospinitcmd
  failed_when: canospinitcmd.rc != 0
  tags:
    - cps_canopsinit
