#!/bin/bash

export PATH="$PATH:/usr/sbin:$HOME/bin"

export PS1='[\u@\h \W]\$ '

if [ -e $HOME/bin/activate ]; then
    . $HOME/bin/activate
fi

if [ -f ~/.bash_completion ]
then
     . ~/.bash_completion
fi

alias ls="ls --color=auto"
alias ll="ls -l"
