---
# tasks file for grafana
- include_tasks: "{{ ansible_os_family }}.yml"

- name: Start Influxdb
  service:
    name: influxdb
    state: started
  when: influxdb_database_name is defined

- name: Create database "{{ influxdb_database_name }}" without credentials
  influxdb_database:
    hostname: "{{influxdb_ip_address}}"
    database_name: "{{influxdb_database_name}}"
    state: present
  when:
    - influxdb_database_name is defined
    - influxdb_username is not defined

- name: Create database "{{ influxdb_database_name }}" using custom credentials
  influxdb_database:
    hostname: "{{influxdb_ip_address}}"
    username: "{{influxdb_username}}"
    password: "{{influxdb_password}}"
    database_name: "{{influxdb_database_name}}"
    state: present
  when: 
    - influxdb_database_name is defined
    - influxdb_username is defined 
