- name: Install Influxdb
  yum:
    name: "influxdb{{ influxdb_version is defined|ternary('-'+influxdb_version|string, '')}}"
    state: present
    disable_gpg_check: yes

- name: Define Config
  template:
    src: influxdb.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Start Influxdb
