---
- name: Reload systemd
  systemd:
    daemon-reload: yes
  tags:
    - cps_services

- name: Start and enable Canopsis webserver
  systemd:
    name: canopsis-webserver
    state: started
    enabled: true
  tags:
    - cps_services

- name: Start and enable Canopsis common engines
  systemd:
    name: "canopsis-engine@{{ item.module }}-{{ item.name }}.service"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  with_items: "{{ canopsis_common_engines }}"
  tags:
    - cps_services
    - cps_common_services

- name: Start and enable Canopsis default Python engines
  systemd:
    name: "canopsis-engine@{{ item.module }}-{{ item.name }}.service"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  with_items: "{{ canopsis_python_engines }}"
  when: canopsis_engines_type == "python"
  tags:
    - cps_services
    - cps_python_services

- name: Start and enable Canopsis default Go engines
  systemd:
    name: "canopsis-engine-go@{{ item.name }}.service"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  with_items: "{{ canopsis_go_engines }}"
  when: canopsis_engines_type == "go"
  tags:
    - cps_services
    - cps_go_services
