---
- name: Reload systemd
  systemd:
    daemon-reload: yes
  tags:
    - cps_services

- name: Start and enable webserver
  systemd:
    name: canopsis-webserver
    state: started
    enabled: true
  tags:
    - cps_services

- name: Start and enable engines
  systemd:
    name: "canopsis-engine@{{ item.module }}-{{ item.name }}.service"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  with_items: "{{ canopsis_engines }}"
  tags:
    - cps_services
