---
- name: Deploy common environment variables for Go engines
  template:
    src: go-engines/go-engines-vars.j2
    dest: "{{ canopsis_home }}/etc/go-engines-vars.conf"

- name: Override initialisation.toml with initialisation.toml.example
  copy:
    src: "{{ canopsis_home }}/etc/initialisation.toml.example"
    dest: "{{ canopsis_home }}/etc/initialisation.toml"
    remote_src: yes

- name: Override amqp2engines.conf with amqp2engines-go.conf.example
  copy:
    src: "{{ canopsis_home }}/etc/amqp2engines-go.conf.example"
    dest: "{{ canopsis_home }}/etc/amqp2engines.conf"
    remote_src: yes
