---
- name: Create canopsis-engine-go .service directory
  file: path=/etc/systemd/system/canopsis-engine-go@.service.d state=directory

- name: Deploy common environment variables for Go engines
  template:
    src: go-engines/all-go-engines.j2
    dest: "/etc/systemd/system/canopsis-engine-go@.service.d/all-go-engines.conf"

- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Override amqp2engines.conf to disable most Python engines
  copy:
    src: go-engines/amqp2engines.conf
    dest: "{{ canopsis_home }}/etc/amqp2engines.conf"
