---
# workaround for https://github.com/ansible/ansible/issues/34153
- name: force pymongo 3.4.0
  pip:
    name: pymongo
    version: 3.4.0

- name: Create canopsis user
  mongodb_user:
    login_database: "admin"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ canopsis_mongo_port }}"
    login_host: "{{ canopsis_mongo_host }}"
    database: "{{ canopsis_mongo_db }}"
    name: "{{ canopsis_mongo_user }}"
    password: "{{ canopsis_mongo_password }}"
    state: present
    roles:
      - 'dbOwner'
