---
- name: "[Debian] Install Rundeck"
  package:
    name: rundeck=3.2.6.20200427-1
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: "[Centos] Install Rundeck"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - java
    - rundeck-3.2.6.20200427-1
  when: ansible_facts['os_family'] == 'RedHat'

- name: Configure Rundeck properties
  lineinfile:
    dest: "/etc/rundeck/rundeck-config.properties"
    line: "{{ item.parameter }} = {{ item.value }}"
    regexp: "^{{ item.parameter }}"
    create: yes
  loop: "{{ rundeck_config }}"
  loop_control:
    label: "{{ item.parameter }}"

- name: Configure Rundeck framework properties
  lineinfile:
    dest: "/etc/rundeck/framework.properties"
    line: "{{ item.parameter }} = {{ item.value }}"
    regexp: "^{{ item.parameter }}"
    create: yes
  loop: "{{ rundeck_framework }}"
  loop_control:
    label: "{{ item.parameter }}"

- name: Configure Rundeck users
  lineinfile:
    dest: "/etc/rundeck/realm.properties"
    line: "{{ item.username }}:{{ item.password }},{{ item.roles }}"
    regexp: "^{{ item.username }}"
  loop: "{{ rundeck_users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Add Rundeck plugins
  get_url:
    url: "{{ item }}"
    dest: /var/lib/rundeck/libext
  loop: "{{ rundeck_addons }}"
  when: rundeck_addons is defined

- name: "[Debian]Change JavaVM memory usage"
  lineinfile:
    dest: "/etc/default/rundeckd"
    line: "RDECK_JVM_SETTINGS=\"-Xmx{{ rundeck_xmx }}m -Xms{{ rundeck_xms }}m -XX:MaxMetaspaceSize={{ rundeck_maxmetaspacesize }}m -server\""
    regexp: "^RDECK_JVM_SETTINGS"
    create: yes
  when: ansible_facts['os_family'] == 'Debian'
 
- name: "[Debian]Change JavaVM memory usage"
  lineinfile:
    dest: "/etc/sysconfig/rundeckd"
    line: "RDECK_JVM_SETTINGS=\"-Xmx{{ rundeck_xmx }}m -Xms{{ rundeck_xms }}m -XX:MaxMetaspaceSize={{ rundeck_maxmetaspacesize }}m -server\""
    regexp: "^RDECK_JVM_SETTINGS"
    create: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Start and enable Rundeck
  service:
    name: rundeckd
    state: restarted
    enabled: yes

- name:  Wait for Rundeck to be up
  uri:
    url: "http://{{ ansible_fqdn }}:4440"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 12
  delay: 5

- name: get rundeck session cookie
  uri:
    url: "http://{{ ansible_fqdn }}:4440/j_security_check"
    method: POST
    body_format: form-urlencoded
    body:
      j_username: admin
      j_password: admin
    status_code: 302
  register: login

- name: Test project Canopsis
  uri:
    url: "http://{{ ansible_fqdn }}:4440/api/11/project/Canopsis"
    method: GET
    headers:
      Cookie: "{{ login.set_cookie }}"
      Content-Type: "application/json"
  register: project
  ignore_errors: True

- name: Create project Canopsis
  uri:
    url: "http://{{ ansible_fqdn }}:4440/api/11/projects"
    method: POST
    body_format: json
    body:
      name: "Canopsis"
      config: {"project.label": "Canopsis jobs"}
    headers:
      Cookie: "{{ login.set_cookie }}"
    status_code: 201
  when: "{{project.status}} != 200"

- name: Import Rundeck jobs
  uri:
    url: "http://{{ ansible_fqdn }}:4440/api/14/project/Canopsis/jobs/import?fileformat=yaml&dupeOption=update&uuidOption=remove"
    method: POST
    src: "{{ canopsis_home }}/etc/rundeck/jobs.yaml"
    headers:
      Cookie: "{{ login.set_cookie }}"
      Content-Type: application/yaml
