---
- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Stop and disable Canopsis default Python engines
  systemd:
    name: "canopsis-engine@{{ item.module }}-{{ item.name }}.service"
    state: stopped
    enabled: false
  with_items: "{{ canopsis_python_engines }}"

- name: Initializing RabbitMQ for Go engines
  shell: "{{ canopsis_home }}/bin/init -conf {{ canopsis_home }}/etc/initialisation-without-engine-stat.toml"
  environment:
    CPS_AMQP_URL: "amqp://{{ canopsis_amqp_userid }}:{{ canopsis_amqp_password }}@{{ canopsis_amqp_host }}:{{ canopsis_amqp_port }}/{{ canopsis_amqp_vhost }}"
  register: go-init-cmd
  failed_when: go-init-cmd.rc != 0

- name: Start and enable Canopsis default Go engines
  systemd:
    name: "canopsis-engine-go@{{ item.name }}.service"
    state: started
    enabled: true
  with_items: "{{ canopsis_go_engines }}"
