---
- name: Init script of postgres
  command: "initdb --auth-host=md5 --locale=en_US.UTF-8 -D /var/lib/pgsql/data" 
  become: yes
  become_user: postgres

# Module error in the venv, using lineinfile instead of postgresql_pg_hba

#- name: Edit pg_hba.conf                                                         
#  become: yes
#  become_user: postgres
#  postgresql_pg_hba:                                                             
#    dest: /var/lib/pgsql/data/pg_hba.conf                                        
#    contype: host                                                                
#    databases: all                                                               
#    users: all                                                                   
#    source: all                                                                  
#    method: md5

- name: Edit pg_hba.conf
  lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: '^host.*127\.0\.0\.1'
    line: "host    all             all             all            md5"

- name: Edit postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: '^listen_addresses'
    line: "listen_addresses = '*'"
    insertbefore: '^#listen_addresses'

- name: Start and enable postgres
  service:
      name: "postgresql"
      state: restarted
      enabled: yes

- name: Create databases                                
  become: yes
  become_user: postgres
  postgresql_db:                                                                 
    name: "{{ item.name }}"
  loop: "{{ postgres_dbs }}"

- name: Create users                                                      
  become: yes
  become_user: postgres
  postgresql_user:                                                               
    name: "{{ item.username }}"
    password: "{{ item.password }}"                                                           
  loop: "{{ postgres_users }}"
                                                                                 
- name: Grant privileges on databases
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ item.db }}" 
    privs: "{{ item.privs }}"
    type: database
    role: "{{ item.role }}"
  loop: "{{ postgres_privs }}"
