---
- name: Start and enable Canopsis common engines
  systemd:
    name: "canopsis-engine@{{ item.module }}-{{ item.name }}.service"
    state: started
    enabled: true
  with_items: "{{ canopsis_common_engines }}"

- name: Start and enable Canopsis webserver
  systemd:
    name: canopsis-webserver
    state: started
    enabled: true
