---
- set_fact:
    pg_data_path: "/var/lib/postgresql/9.6/main/"
    pg_conf_path: "/etc/postgresql/9.6/main/"
    pg_service: "postgresql"
  when: ansible_facts['os_family'] == 'Debian'

- set_fact:
    pg_data_path: "/var/opt/rh/rh-postgresql96/lib/pgsql/data/"
    pg_conf_path: "/var/opt/rh/rh-postgresql96/lib/pgsql/data/"
    pg_service: "rh-postgresql96-postgresql"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Test if postgres is already installed
  stat:
    path: "{{pg_conf_path}}/pg_hba.conf"
  register: pgsql

- name: Init script of postgres
  command: "/opt/rh/rh-postgresql96/root/usr/bin/initdb --auth-host=md5 --locale=en_US.UTF-8 -D {{pg_data_path}}"
  become: yes
  become_user: postgres
  when:
    - pgsql.stat.isdir is not defined # and pgsql.stat.isdir
    - ansible_facts['os_family'] == 'RedHat'

# Module error in the venv, using lineinfile instead of postgresql_pg_hba

#- name: Edit pg_hba.conf                                                         
#  become: yes
#  become_user: postgres
#  postgresql_pg_hba:                                                             
#    dest: /var/lib/pgsql/data/pg_hba.conf                                        
#    contype: host                                                                
#    databases: all                                                               
#    users: all                                                                   
#    source: all                                                                  
#    method: md5

- name: Edit pg_hba.conf
  lineinfile:
    path: "{{pg_conf_path}}pg_hba.conf"
    regexp: '^host.*127\.0\.0\.1'
    line: "host    all             all             all            md5"

- name: Edit postgresql.conf
  lineinfile:
    path: "{{ pg_conf_path }}postgresql.conf"
    regexp: '^listen_addresses'
    line: "listen_addresses = '*'"
    insertbefore: '^#listen_addresses'

- name: Start and enable postgres
  service:
      name: "{{ pg_service }}"
      state: restarted
      enabled: yes

- name: Create databases                                
  become: yes
  become_user: postgres
  postgresql_db:                                                                 
    name: "{{ item.name }}"
  loop: "{{ postgres_dbs }}"

- name: Create users                                                      
  become: yes
  become_user: postgres
  postgresql_user:                                                               
    name: "{{ item.username }}"
    password: "{{ item.password }}"                                                           
  loop: "{{ postgres_users }}"
                                                                                 
- name: Grant privileges on databases
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ item.db }}" 
    privs: "{{ item.privs }}"
    type: database
    role: "{{ item.role }}"
  loop: "{{ postgres_privs }}"
