---
- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Stop and disable Canopsis default Python engines
  systemd:
    name: "canopsis-engine@{{ item.module }}-{{ item.name }}.service"
    state: stopped
    enabled: false
  with_items: "{{ canopsis_python_engines }}"
  register: ansiblecrap
  failed_when: "ansiblecrap is failed and 'Could not find the requested service' not in ansiblecrap.msg"

- name: Initializing RabbitMQ for Go engines
  shell: "eval $(grep -v '^#' /opt/canopsis/etc/go-engines-vars.conf | sed 's/^/export /') && {{ canopsis_home }}/bin/init -conf {{ canopsis_home }}/etc/initialisation.toml"
  environment:
    CPS_WAIT_FIRST_ATTEMPT: 2
    CPS_MAX_RETRY: 3
  register: goinitcmd
  failed_when: goinitcmd.rc != 0

- name: Start and enable Canopsis default Go engines
  systemd:
    name: "canopsis-engine-go@{{ item.name }}.service"
    state: started
    enabled: true
  with_items: "{{ canopsis_go_engines }}"

- name: Start and enable Canopsis default Go engines (CAT additions)
  systemd:
    name: "canopsis-engine-go@{{ item.name }}.service"
    state: started
    enabled: true
  with_items: "{{ canopsis_cat_go_additional_engines }}"
  when: canopsis_edition == "cat"
