ARG GOLANG_IMAGE_TAG

FROM golang:${GOLANG_IMAGE_TAG}

ENV GO111MODULE on

RUN apk update && apk add make git curl gcc build-base g++

WORKDIR /go/src/community/go-engines-community
COPY . . 
COPY docker/go-test.sh /go-test.sh

RUN go mod download

# do not set entrypoint as this container will be run via docker-compose exec
