# Args defined here are only available to FROM commands
# See https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG ALPINE_BUILD_VERSION
ARG GOLANG_VERSION

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_BUILD_VERSION}

RUN apk add --no-cache make git gcc binutils binutils-gold libc-dev

WORKDIR /go/src
COPY . . 
COPY community/go-engines-community/go-test.sh /go-test.sh

RUN cd community/go-engines-community && go mod download

# do not set entrypoint as this container will be run via docker-compose exec
