#!/usr/bin/env python
# -*- coding: utf-8 -*-
# --------------------------------
# Copyright (c) 2015 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

from canopsis.migration.manager import MigrationTool
from argparse import ArgumentParser


if __name__ == '__main__':
    parser = ArgumentParser(description='Canopsis Migration Tool')
    parser.add_argument('--init', dest='init', action='store_true')
    parser.add_argument('--update', dest='init', action='store_false')
    parser.set_defaults(init=True)

    args = parser.parse_args()

    mgr = MigrationTool()
    mgr.fill(init=args.init)
