ARG GOLANG_IMAGE_TAG

FROM golang:${GOLANG_IMAGE_TAG}

ENV CGO_ENABLED=1

RUN apk update && apk add make git gcc build-base g++

WORKDIR /go/src/canopsis
COPY . .

RUN rm -rf vendor && go mod download
