ARG GOLANG_IMAGE_TAG

FROM golang:${GOLANG_IMAGE_TAG}

ENV GO111MODULE on

RUN apk update && apk add make git

WORKDIR /go/src/community/go-engines-community
COPY . .

ENV RELEASES_DIR /releases/

# do not set entrypoint as this container will be run via docker-compose exec
