- src: https://github.com/geerlingguy/ansible-role-haproxy
  scm: git

# adapted to our deployment needs
#- src: https://github.com/UnderGreen/ansible-role-mongodb
#  scm: git

# upgraded from 3.6.11 to 3.6.14. Poorly maintained upstream
#- src: https://github.com/geerlingguy/ansible-role-rabbitmq
#  scm: git

- src: https://github.com/geerlingguy/ansible-role-redis
  scm: git

- src: https://gitlab.capensis.fr/projet-maat/ansible-role-repository-adder-maat
  scm: git

# broken
#- src: https://gitlab.capensis.fr/projet-maat/ansible-role-influxdb-maat
#  version: debian_compat
#  scm: git
