// Code generated by MockGen. DO NOT EDIT.
// Source: git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/api/httperror (interfaces: Responder)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/lib/api/httperror/httperror.go git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/api/httperror Responder
//

// Package mock_httperror is a generated GoMock package.
package mock_httperror

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	fastjson "github.com/valyala/fastjson"
	gomock "go.uber.org/mock/gomock"
)

// MockResponder is a mock of Responder interface.
type MockResponder struct {
	ctrl     *gomock.Controller
	recorder *MockResponderMockRecorder
	isgomock struct{}
}

// MockResponderMockRecorder is the mock recorder for MockResponder.
type MockResponderMockRecorder struct {
	mock *MockResponder
}

// NewMockResponder creates a new mock instance.
func NewMockResponder(ctrl *gomock.Controller) *MockResponder {
	mock := &MockResponder{ctrl: ctrl}
	mock.recorder = &MockResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponder) EXPECT() *MockResponderMockRecorder {
	return m.recorder
}

// GetResponse mocks base method.
func (m *MockResponder) GetResponse(c *gin.Context, err error) (int, *fastjson.Value) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponse", c, err)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*fastjson.Value)
	return ret0, ret1
}

// GetResponse indicates an expected call of GetResponse.
func (mr *MockResponderMockRecorder) GetResponse(c, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponse", reflect.TypeOf((*MockResponder)(nil).GetResponse), c, err)
}

// Respond mocks base method.
func (m *MockResponder) Respond(c *gin.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Respond", c, err)
}

// Respond indicates an expected call of Respond.
func (mr *MockResponderMockRecorder) Respond(c, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Respond", reflect.TypeOf((*MockResponder)(nil).Respond), c, err)
}
