FROM debian:jessie-slim

ARG PROXY

ENV http_proxy ${PROXY}
ENV https_proxy ${PROXY}

RUN apt-get update && apt-get install -y bash && apt-get clean

COPY docker/build/debian-jessie-run.sh /
RUN /bin/bash /debian-jessie-run.sh

COPY docker/files/vimrc /root/.vimrc
COPY docker/files/bashrc /root/.bashrc