ARG SYSBASE

FROM canopsis/canopsis-sysbase:${SYSBASE}

ARG SYSBASE
ARG PROXY

ENV http_proxy ${PROXY}
ENV https_proxy ${PROXY}

COPY docker/build/run-${SYSBASE}.sh /run.sh
RUN /bin/bash /run-${SYSBASE}.sh /run.sh

COPY docker/build/build-${SYSBASE}.sh /build.sh
RUN /bin/bash /build.sh

COPY sources/externals/python-libs /sources/python-libs
COPY sources/canopsis /sources/canopsis

COPY docker/build/pip-wheel.sh /

ENTRYPOINT ["/bin/bash", "/pip-wheel.sh"]
