FROM debian:jessie-slim

ARG PROXY

ENV http_proxy ${PROXY}
ENV https_proxy ${PROXY}

COPY docker/build/debian-jessie-run.sh /
RUN /bin/sh /debian-jessie-run.sh

COPY docker/files/vimrc /root/.vimrc
COPY docker/files/bashrc /root/.bashrc