FROM node:10.6-alpine AS build

WORKDIR /canopsis-next
COPY sources/webcore/src/canopsis-next /canopsis-next
RUN yarn && yarn build

FROM nginx:1.17.10-alpine

COPY docker/files/etc/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY docker/files/entrypoint-nginx.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /opt/canopsis/var/www/src/canopsis-next/dist

COPY --from=build /canopsis-next/dist /opt/canopsis/var/www/src/canopsis-next/dist

EXPOSE 8080

ENTRYPOINT /entrypoint.sh
