FROM nginx:1.17.10-alpine

COPY docker/files/etc/nginx/default.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /etc/nginx/conf.d/locations.d/
COPY docker/files/entrypoint-nginx.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT /entrypoint.sh
