#!/bin/sh

cat > /etc/yum.repos.d/mongodb-org.repo << EOF
[mongodb-org-3.4]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/3.4/\$basearch/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc
EOF

yum clean all
yum update -y

yum install -y epel-release
yum install -y xz make gcc gcc-c++ zlib-devel libevent-devel libevent ncurses-devel libcurl-devel wget libtool openssl openssl-devel bzip2-devel cyrus-sasl-devel openldap-devel libcurl-devel python-devel openldap-devel libxml2-devel libxslt-devel perl-ExtUtils-MakeMaker git rsync librsync-devel uthash-devel.noarch libacl-devel openssl* ncurses* libxml2-devel libxslt-devel xmlsec1-devel libffi-devel xmlsec1-openssl-devel libtool-ltdl-devel python-virtualenv

# erlang for rabbitmq-server
yum install -y erlang

# mongodb
yum install -y mongodb-org mongodb-org-tools
