#!/bin/sh
apt-get update

apt-get install -y libevent-dev bzip2 build-essential zlib1g-dev libreadline5-dev libdb4.8-dev libncurses5-dev libexpat1-dev xmlto libcurl4-gnutls-dev git-core libssl-dev libpcre3-dev libsqlite3-dev automake libtool libcairo2-dev uuid-runtime zlib1g-dev xsltproc curl libbz2-dev xvfb
