#!/bin/sh
yum clean all
yum update -y

yum install -y epel-release
yum install -y xz make gcc gcc-c++ zlib-devel libevent-devel libevent ncurses-devel libcurl-devel wget libtool openssl openssl-devel bzip2-devel cyrus-sasl-devel openldap-devel libcurl-devel python-devel openldap-devel libxml2-devel libxslt-devel perl-ExtUtils-MakeMaker git erlang rsync  librsync-devel uthash-devel.noarch libacl-devel openssl* ncurses* libxml2-devel libxslt-devel xmlsec1-devel
