---
version: '2'
volumes:
  mongodbdata:
    driver: local
  influxdbdata:
    driver: local
  rabbitmqdata:
    driver: local
  importctxdata:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_TAG}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 2g
    oom_score_adj: -1000
    environment:
      - RABBITMQ_DEFAULT_USER=cpsrabbit
      - RABBITMQ_DEFAULT_PASS=canopsis
      - RABBITMQ_DEFAULT_VHOST=canopsis
  mongodb:
    image: mongo:${MONGODB_TAG}
    env_file: compose.mongo.env
    ports:
      - "27027:27017"
    volumes:
      - mongodbdata:/data/db
      - "./files/mongo/:/docker-entrypoint-initdb.d"
    restart: unless-stopped
    mem_limit: 3g
    mem_reservation: 3g
    oom_score_adj: -1000
    command: '--wiredTigerCacheSizeGB 2560'
  influxdb:
    image: influxdb:${INFLUX_TAG}
    ports:
      - "8086:8086"
      - "4444:4444/udp"
      - "8083:8083"
    restart: unless-stopped
    mem_limit: 3g
    mem_reservation: 3g
    oom_score_adj: -1000
    environment:
      - INFLUXDB_DB=canopsis
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=cpsinflux
      - INFLUXDB_USER_PASSWORD=canopsis
    volumes:
      - influxdbdata:/var/lib/influxdb
  redis:
    image: redis:${REDIS_TAG}
    restart: unless-stopped
    ports:
      - 6379:6379
  nginx:
    image: canopsis/nginx:${CANOPSIS_IMAGE_TAG}
    ports:
      - "80:80"
    env_file:
      - compose.env
    environment:
      - TARGET=http://webserver:8082
    depends_on:
      - "webserver"
    restart: unless-stopped
  provisionning:
    image: canopsis/canopsis-prov:${CANOPSIS_IMAGE_TAG}
    environment:
      - CPS_STACK=go
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    restart: "no"
  pbehavior:
    image: canopsis/canopsis-core:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=pbehavior
      - ENGINE_MODULE=canopsis.engines.dynamic
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  action:
    image: canopsis/engine-action:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-action
  heartbeat:
    image: canopsis/engine-heartbeat:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-heartbeat
  axe:
    image: canopsis/engine-axe:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-axe
  che:
    image: canopsis/engine-che:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-che -d -publishQueue Engine_axe
  fifo:
    image: canopsis/engine-fifo:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-fifo
  watcher:
    image: canopsis/engine-watcher:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
  scheduler:
    image: canopsis/canopsis-core:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=scheduler
      - ENGINE_MODULE=canopsis.engines.scheduler
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  task_importctx:
    image: canopsis/canopsis-core:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    environment:
      - ENGINE_NAME=task_importctx
      - ENGINE_MODULE=canopsis.engines.task_importctx
    volumes:
      - importctxdata:/opt/canopsis/tmp
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  metric:
    image: canopsis/canopsis-core:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    depends_on:
      - "influxdb"
    environment:
      - ENGINE_NAME=metric
      - ENGINE_MODULE=canopsis.engines.metric
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 200m
  webserver:
    image: canopsis/canopsis-core:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    environment:
      - CPS_WEBSERVER=1
    depends_on:
      - "mongodb"
    ports:
      - 8082:8082
    volumes:
      - importctxdata:/opt/canopsis/tmp
      - "../docker/files/entrypoint.sh:/entrypoint.sh"
    links:
      - mongodb
      - rabbitmq
      - influxdb
    restart: unless-stopped
  init:
    image: canopsis/init:${CANOPSIS_IMAGE_TAG}
    depends_on:
      - "rabbitmq"
      - "mongodb"
    env_file:
      - compose.env
