BEGIN;

DROP TABLE IF EXISTS fifo_queue;
DROP TABLE IF EXISTS fifo_event;
DROP TABLE IF EXISTS che_event;
DROP TABLE IF EXISTS axe_event;
DROP TABLE IF EXISTS axe_periodical;
DROP TABLE IF EXISTS pbehavior_periodical;
DROP TABLE IF EXISTS che_infos;

COMMIT;
