// Code generated by MockGen. DO NOT EDIT.
// Source: lib/canopsis/idlerule/rule_adapter.go

// Package mock_idlerule is a generated GoMock package.
package mock_idlerule

import (
	idlerule "git.canopsis.net/canopsis/go-engines/lib/canopsis/idlerule"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRuleAdapter is a mock of RuleAdapter interface
type MockRuleAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockRuleAdapterMockRecorder
}

// MockRuleAdapterMockRecorder is the mock recorder for MockRuleAdapter
type MockRuleAdapterMockRecorder struct {
	mock *MockRuleAdapter
}

// NewMockRuleAdapter creates a new mock instance
func NewMockRuleAdapter(ctrl *gomock.Controller) *MockRuleAdapter {
	mock := &MockRuleAdapter{ctrl: ctrl}
	mock.recorder = &MockRuleAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRuleAdapter) EXPECT() *MockRuleAdapterMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockRuleAdapter) Get() ([]idlerule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]idlerule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRuleAdapterMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRuleAdapter)(nil).Get))
}
