// Code generated by MockGen. DO NOT EDIT.
// Source: git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/datastorage (interfaces: Adapter,Cleaner)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/lib/canopsis/datastorage/adapter.go git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/datastorage Adapter,Cleaner
//

// Package mock_datastorage is a generated GoMock package.
package mock_datastorage

import (
	context "context"
	reflect "reflect"

	datastorage "git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/datastorage"
	datetime "git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/canopsis/datetime"
	mongo "git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAdapter) Get(ctx context.Context) (datastorage.DataStorage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(datastorage.DataStorage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdapterMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdapter)(nil).Get), ctx)
}

// UpdateHistoryEntityCleaned mocks base method.
func (m *MockAdapter) UpdateHistoryEntityCleaned(ctx context.Context, history datastorage.HistoryWithCount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHistoryEntityCleaned", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHistoryEntityCleaned indicates an expected call of UpdateHistoryEntityCleaned.
func (mr *MockAdapterMockRecorder) UpdateHistoryEntityCleaned(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHistoryEntityCleaned", reflect.TypeOf((*MockAdapter)(nil).UpdateHistoryEntityCleaned), ctx, history)
}

// UpdateHistoryEntityDisabled mocks base method.
func (m *MockAdapter) UpdateHistoryEntityDisabled(ctx context.Context, history datastorage.HistoryWithCount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHistoryEntityDisabled", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHistoryEntityDisabled indicates an expected call of UpdateHistoryEntityDisabled.
func (mr *MockAdapterMockRecorder) UpdateHistoryEntityDisabled(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHistoryEntityDisabled", reflect.TypeOf((*MockAdapter)(nil).UpdateHistoryEntityDisabled), ctx, history)
}

// UpdateHistoryEntityUnlinked mocks base method.
func (m *MockAdapter) UpdateHistoryEntityUnlinked(ctx context.Context, history datastorage.HistoryWithCount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHistoryEntityUnlinked", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHistoryEntityUnlinked indicates an expected call of UpdateHistoryEntityUnlinked.
func (mr *MockAdapterMockRecorder) UpdateHistoryEntityUnlinked(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHistoryEntityUnlinked", reflect.TypeOf((*MockAdapter)(nil).UpdateHistoryEntityUnlinked), ctx, history)
}

// MockCleaner is a mock of Cleaner interface.
type MockCleaner struct {
	ctrl     *gomock.Controller
	recorder *MockCleanerMockRecorder
	isgomock struct{}
}

// MockCleanerMockRecorder is the mock recorder for MockCleaner.
type MockCleanerMockRecorder struct {
	mock *MockCleaner
}

// NewMockCleaner creates a new mock instance.
func NewMockCleaner(ctrl *gomock.Controller) *MockCleaner {
	mock := &MockCleaner{ctrl: ctrl}
	mock.recorder = &MockCleanerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleaner) EXPECT() *MockCleanerMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockCleaner) Clean(ctx context.Context, dbClient mongo.DbClient, conf datastorage.Config, t datetime.CpsTime, limit int) (datastorage.CleanResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, dbClient, conf, t, limit)
	ret0, _ := ret[0].(datastorage.CleanResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockCleanerMockRecorder) Clean(ctx, dbClient, conf, t, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockCleaner)(nil).Clean), ctx, dbClient, conf, t, limit)
}

// IsEnabled mocks base method.
func (m *MockCleaner) IsEnabled(conf datastorage.Config) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", conf)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockCleanerMockRecorder) IsEnabled(conf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockCleaner)(nil).IsEnabled), conf)
}
