<template>
  <svg
    width="45"
    height="36"
    viewBox="0 0 45 36"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="0.5"
      y="1.17773"
      width="44"
      height="34"
      rx="4.5"
      fill="currentColor"
      fill-opacity="0.4"
      stroke="currentColor"
    />
  </svg>
</template>
