(* KEYWORDS *)

@@keyword :: ALL
@@keyword :: TRUE FALSE NULL
@@keyword :: AND OR
@@keyword :: IN NIN LIKE

(*/KEYWORDS *)

(* TYPES *)
true::true = "TRUE" ;
false::false = "FALSE" ;
digits::digits = value:/[0-9]+/ ;
characters::characters = value:/\w*/ ;

string::forward_value = '"' value:characters '"' | "'" value:characters "'" ;
sign::sign = value:( "+" | "-" ) ;
integer::integer = [ sign:sign ] value:digits ;
floating::floating = [ sign:sign ] intpart:digits "." floatpart:digits ;
boolean::forward_value = value:( true | false ) ;
none::none = "NULL";
(*/TYPES *)

(* GENERIC *)
@name
key::forward_value = value:( /[_a-zA-Z][_a-zA-Z0-9]*(\.[_a-zA-Z][_a-zA-Z0-9]*)*/ ) ;
value::forward_value = value:( string | floating | integer | boolean | none ) ;
(*/GENERIC *)

(* CONDITION *)
condop::condop = value:( "AND" | "OR" | "<=" | "<" | "=" | "!=" | ">=" | ">" | "IN" | "NIN" | "LIKE" ) ;
condition::condition = "(" left:key condop:condop right:value ")" ;
(*/CONDITION *)

start = condition:condition ;
