#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	    CREATE DATABASE "$PG_CANOPSIS_DB";
	    CREATE USER "$PG_CANOPSIS_USER" WITH PASSWORD '${PG_CANOPSIS_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE "$PG_CANOPSIS_DB" to "$PG_CANOPSIS_USER";
        \c "$PG_CANOPSIS_DB";
        GRANT ALL ON SCHEMA public TO "$PG_CANOPSIS_USER";
        CREATE EXTENSION IF NOT EXISTS timescaledb;
EOSQL