#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "$PG_TECHMETRICS_DB";
	CREATE USER "$PG_TECHMETRICS_USER" WITH PASSWORD '${PG_TECHMETRICS_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE "$PG_TECHMETRICS_DB" to "$PG_TECHMETRICS_USER";
        \c "$PG_TECHMETRICS_DB";
        GRANT ALL ON SCHEMA public TO "$PG_TECHMETRICS_USER";
        CREATE EXTENSION IF NOT EXISTS timescaledb;
EOSQL
