#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "$TECHMETRICS_DB";
	CREATE USER "$TECHMETRICS_USER" WITH PASSWORD '${TECHMETRICS_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE "$TECHMETRICS_DB" to "$TECHMETRICS_USER";
        \c "$TECHMETRICS_DB";
        GRANT ALL ON SCHEMA public TO "$TECHMETRICS_USER";
        CREATE EXTENSION IF NOT EXISTS timescaledb;
EOSQL
