# Default values for canopsis
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

RABBITMQ_TAG: 3-management
MONGO_TAG: 3.6-jessie
CANOPSIS_IMAGE_TAG: 3.12.0
INFLUX_TAG: 1.5-alpine
REDIS_TAG: '4.0'
MONGO_PERSISTENT_VOLUME: /tmp/mongo1
MONGO_VOLUME: /Datas/canopsis/docker/mongo
