# -*- coding: utf-8 -*-
# --------------------------------
# Copyright (c) 2019 "Capensis" [http://www.capensis.com]
#
# This file is part of Canopsis.
#
# Canopsis is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Canopsis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Canopsis.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------

from __future__ import unicode_literals


class Stats(object):
    """
    Stats is an object containing the stat counters that can be displayed in
    the service weather modals, using the data generated by the go engine
    `engine-stat`.

    :param int ok_count: The number of check events received with
        state 0.
    :param int ko_count: The number of check events received with
        state 1, 2 or 3.
    :param Union[int, None] last_ko: The timestamp of the last event received
        with state 1, 2, or 3.
    :param Union[int, None] last_event: The timestamp of the last event
        received.
    """
    def __init__(self, ok_count, ko_count, last_ko, last_event):
        self.ok_count = ok_count
        self.ko_count = ko_count
        self.last_ko = last_ko
        self.last_event = last_event

    def as_dict(self):
        """
        Return the object as a dictionary.
        """
        return {
            'ok': self.ok_count,
            'ko': self.ko_count,
            'last_ko': self.last_ko,
            'last_event': self.last_event
        }
