map:
  /api/v2/entities:
    GET: [api_entity_read,can]
  /get-entities:
    GET: [api_entity_read,can]
  /put-entities:
    PUT: [api_entity_update,can]
  /update-entity:
    PUT: [api_entity_update,can]
  /delete-entity:
    PUT: [api_entity_delete,can]
  /api/v2/alerts/filters:
    POST: [api_alarmfilter,create]
    GET: [api_alarmfilter,read]
    PUT: [api_alarmfilter,update]
    DELETE: [api_alarmfilter,delete]
  /api/v2/alerts/done:
    GET: [api_alarm_update,can]
  /api/v2/alerts:
    GET: [api_alarm_read,can]
    DELETE: [api_alarm_delete,can]
  /api/v2/idle-rule:
    POST: [api_idlerule,create]
    GET: [api_idlerule,read]
    PUT: [api_idlerule,update]
    DELETE: [api_idlerule,delete]
  /api/v2/eventfilter/rules:
    POST: [api_eventfilter,create]
    GET: [api_eventfilter,read]
    PUT: [api_eventfilter,update]
    DELETE: [api_eventfilter,delete]
  /api/v2/metaalarmrule:
    POST: [api_metaalarmrule,create]
    GET: [api_metaalarmrule,read]
    PUT: [api_metaalarmrule,update]
    DELETE: [api_metaalarmrule,delete]
  /api/v2/playlist:
    POST: [api_playlist,create]
    GET: [api_playlist,read]
    PUT: [api_playlist,update]
    DELETE: [api_playlist,delete]
  /api/v2/dynamic-infos:
    POST: [api_dynamicinfos,create]
    GET: [api_dynamicinfos,read]
    PUT: [api_dynamicinfos,update]
    DELETE: [api_dynamicinfos,delete]
  /api/v2/watcherng:
    POST: [api_entityservice,create]
    GET: [api_entityservice,read]
    PUT: [api_entityservice,update]
    DELETE: [api_entityservice,delete]
  /api/v2/watchers:
    POST: [api_entityservice,create]
    GET: [api_entityservice,read]
    PUT: [api_entityservice,update]
    DELETE: [api_entityservice,delete]
  /api/v2/weather/watchers:
    GET: [api_entityservice,read]
  /api/v2/event:
    POST: [api_event,can]
  /event:
    POST: [api_event,can]
    PUT: [api_event,can]
  /api/v2/views/groups:
    POST: [api_viewgroup,create]
    GET: [api_viewgroup,read]
    PUT: [api_viewgroup,update]
    DELETE: [api_viewgroup,delete]
  /api/v2/views:
    POST: [api_view,create]
    GET: [api_view,read]
    PUT: [api_view,update]
    DELETE: [api_view,delete]
