#!/bin/bash

export PATH="$PATH:/usr/sbin"

if [ -e $HOME/bin/activate ]
then
    export PS1="[\h]-[\w]\$ "
    . $HOME/bin/activate
else
    export PS1="\[\033[31;01m\][\h]-[\w]\$\[033[00m\] "
fi

if [ -f ~/.bash_completion ]
then
     . ~/.bash_completion
fi

alias ls="ls --color=auto"
alias ll="ls -l"
