#!/bin/bash

DB="canopsis"

function get_size {
	SIZE=`echo "db.$1.dataSize()" | mongo --quiet $DB | grep -v '>' | grep -v 'utf8' | tail -n 1`
	if [ "$SIZE" = "" ]; then
		SIZE=0
	fi
	echo "$SIZE"
}

DSIZE=`get_size "perfdata"`
FSIZE=`get_size "perfdata.fs.files"`
CSIZE=`get_size "perfdata.fs.chunks"`

TOTAL=$((DSIZE + FSIZE + CSIZE))

echo "Ok|total="$TOTAL"o perfdata="$DSIZE"o fs="$(($FSIZE+$CSIZE))"o"
exit 0
