#!/bin/bash

function start(){
	service rabbitmq-server start
	service mongodb start
	service redis-server start
	service amqp2engines start
	service celeryd start
	service apsd start
	service websocket start
	service webserver start
	service collectd start
	
	if [ -e "$HOME/etc/supervisord.d/gelf2amqp.conf" ]; then
		service gelf2amqp start
	fi
	
}

function stop(){
	service collectd stop
	service websocket stop
	service webserver stop
	service apsd stop
	service celeryd stop
	service amqp2engines stop
	service redis-server stop
	service mongodb stop
	service rabbitmq-server stop
	
	if [ -e "$HOME/etc/supervisord.d/gelf2amqp.conf" ]; then
		service gelf2amqp stop
	fi

	supervisorctl shutdown
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        sleep 1
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
