#!/bin/bash

if [ ! -d .git ];
then
    echo ".git dir not found!"
    exit 1
fi

LINK=1
if [ "x$1" == "x-u" ]; then
	LINK=0
fi

SRC=`pwd`
CPS="/opt/canopsis"

rm -R $CPS/opt/webcore
rm -Rf $CPS/var/www/canopsis
rm -Rf $CPS/var/www/webcore-libs
rm -R $CPS/lib/canolibs
rm -R $CPS/opt/snmp2amqp
rm -R $CPS/var/snmp
rm -R $CPS/opt/collectd-libs
rm -R $CPS/opt/amqp2engines
rm -R $CPS/opt/mongodb

if [ $LINK -eq 1 ]; then
	ln -s $SRC/sources/externals/webcore-libs $CPS/var/www/
	ln -s $SRC/sources/webcore/opt/webcore $CPS/opt/
	ln -s $SRC/sources/webcore/var/www/canopsis $CPS/var/www/
	ln -s $SRC/sources/canolibs/lib/canolibs $CPS/lib/
	ln -s $SRC/sources/snmp2amqp/opt/snmp2amqp $CPS/opt/
	ln -s $SRC/sources/snmp2amqp/var/snmp $CPS/var/
	ln -s $SRC/sources/collectd-libs/opt/collectd-libs $CPS/opt/
	ln -s $SRC/sources/amqp2engines/opt/amqp2engines $CPS/opt/
	ln -s $SRC/sources/mongodb-conf/opt/mongodb $CPS/opt/
fi


