#!/bin/bash

function create_python_slink() {
    # create slink for specific python project
    # first argument is the project, second if given is the version (default 0.1)
    if [ -f $1 ]; then exit 1; fi;
    project=$1
    if [ -f $2 ];
        then version="0.1";
        else version=$2;
    fi;
    # ln -s $SRC/sources/python/$project/canopsis $CPS/lib/python2.7/site-packages/canopsis.$project-$version-py2.7.egg/
}

function create_canolibs_slink() {
    # call create_python_slink on all canolib projects
    cd $SRC/sources/python
    for project_path in $SRC/sources/python/*;
    do
        if [ -d "$project_path" ]; then
            if [ -e "$project_path/canopsis" ]; then
                project_name=$(basename $project_path);
                create_python_slink $project_name;
            fi
        fi
    done
    cd - > /dev/null
}

function create_slinks() {
    # ln -s $SRC/sources/wkhtmltopdf-libs/lib/wkhtmltopdf/* $CPS/lib/wkhtmltopdf/
    # ln -s $SRC/sources/wkhtmltopdf-libs/etc/tasks.d/task_reporting.py $CPS/etc/tasks.d/
    # ln -s $SRC/sources/externals/webcore-libs $CPS/src/
    # ln -s $SRC/sources/webcore/opt/webcore $CPS/opt/
    # ln -s $SRC/sources/webcore/var/plugins $CPS/var/plugins
    ln -s $SRC/sources/webcore/src/canopsis $CPS/var/www/
    ln -s $SRC/sources/webcore/src/login $CPS/var/www/
    ln -s $SRC/sources/collectd-libs/opt/collectd-libs $CPS/opt/
    ln -s $SRC/sources/mongodb-conf/opt/mongodb $CPS/opt/
    ln -s $SRC/sources/mongodb-conf/etc/schema.d $CPS/etc/
    # canolibs
    create_canolibs_slink
    # create_python_slink cli 0.1
    # create_python_slink common 0.1
    # create_python_slink configuration 0.1
    # create_python_slink connectors 0.1
    # create_python_slink context 0.1
    # create_python_slink engines 0.1
    # create_python_slink mongo 0.1
    # create_python_slink old 0.1
    # create_python_slink organisation 0.1
    # create_python_slink perfdata 0.1
    # create_python_slink storage 0.1
    # create_python_slink timeserie 0.1
    # create_python_slink tools 0.1
    # create_python_slink topology 0.1
    # create_python_slink auth 0.1
    # create_python_slink middleware 0.1
    # create_python_slink mom 0.1
    # create_python_slink rpc 0.1

    ln -s $SRC/sources/python/connectors/var/snmp $CPS/var/
    ln -s $SRC/sources/python/webcore/canopsis $CPS/lib/python2.7/site-packages/canopsis.webcore-0.8-py2.7.egg/
    touch $CPS/.slinked
}

function remove_slinks() {
    rm -Rf $CPS/opt/webcore
    rm -Rf $CPS/opt/collectd-libs
    rm -Rf $CPS/opt/mongodb
    rm -Rf $CPS/var/www/canopsis
    rm -Rf $CPS/var/www/login
    rm -Rf $CPS/var/www/webcore-libs
    rm -Rf $CPS/lib/wkhtmltopdf/*
    rm -Rf $CPS/etc/schema.d
    rm -Rf $CPS/etc/tasks.d/task_reporting.py
    rm -rf $CPS/var/plugins

    # canolibs
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.*-py2.7.egg/canopsis

    rm -Rf $CPS/var/snmp
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.webcore-0.8-py2.7.egg/canopsis/webcore/services
    rm $CPS/.slinked 2>/dev/null
}
