#!/bin/bash

function create_slinks() {
    ln -s $SRC/sources/wkhtmltopdf-libs/lib/wkhtmltopdf/* $CPS/lib/wkhtmltopdf/
    ln -s $SRC/sources/wkhtmltopdf-libs/etc/tasks.d/task_reporting.py $CPS/etc/tasks.d/
    ln -s $SRC/sources/externals/webcore-libs $CPS/var/www/
    ln -s $SRC/sources/webcore/opt/webcore $CPS/opt/
    ln -s $SRC/sources/webcore/var/www/canopsis $CPS/var/www/
    ln -s $SRC/sources/collectd-libs/opt/collectd-libs $CPS/opt/
    ln -s $SRC/sources/mongodb-conf/opt/mongodb $CPS/opt/
    ln -s $SRC/sources/mongodb-conf/etc/schema.d $CPS/etc/
    # canolibs
    ln -s $SRC/sources/canolibs/cli $CPS/lib/python2.7/site-packages/canopsis.cli-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/common $CPS/lib/python2.7/site-packages/canopsis.common-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/connectors $CPS/lib/python2.7/site-packages/canopsis.connectors-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/connectors/var/snmp $CPS/var/
    ln -s $SRC/sources/canolibs/context $CPS/lib/python2.7/site-packages/canopsis.context-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/engines $CPS/lib/python2.7/site-packages/canopsis.engines-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/mongo $CPS/lib/python2.7/site-packages/canopsis.mongo-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/old $CPS/lib/python2.7/site-packages/canopsis.old-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/organisation $CPS/lib/python2.7/site-packages/canopsis.organisation-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/perfdata $CPS/lib/python2.7/site-packages/canopsis.perfdata-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/pyperfstore2 $CPS/lib/python2.7/site-packages/pyperfstore2-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/storage $CPS/lib/python2.7/site-packages/canopsis.storage-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/timeserie $CPS/lib/python2.7/site-packages/canopsis.timeserie-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/tools $CPS/lib/python2.7/site-packages/canopsis.tools-0.1-py2.7.egg/
    ln -s $SRC/sources/canolibs/topology $CPS/lib/python2.7/site-packages/canopsis.topology-0.1-py2.7.egg/

    touch $CPS/.slinked
}

function remove_slinks() {
    rm -Rf $CPS/opt/webcore
    rm -Rf $CPS/opt/collectd-libs
    rm -Rf $CPS/opt/mongodb
    rm -Rf $CPS/var/www/canopsis
    rm -Rf $CPS/var/www/webcore-libs
    rm -Rf $CPS/lib/wkhtmltopdf/*
    rm -Rf $CPS/etc/schema.d
    rm -Rf $CPS/etc/tasks.d/task_reporting.py
    # canolibs
    rm -Rf $CPS/lib/python2.7/site-packages/cli-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/common-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/configuration-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/connectors-0.1-py2.7.egg/*
    rm -Rf $CPS/var/snmp
    rm -Rf $CPS/lib/python2.7/site-packages/context-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/engines-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/mongo-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/old-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/organisation-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/perfdata-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/pyperfstore2-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/storage-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/timeserie-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/tools-0.1-py2.7.egg/*
    rm -Rf $CPS/lib/python2.7/site-packages/topology-0.1-py2.7.egg/*
    rm $CPS/.slinked 2>/dev/null
}
