#!/bin/bash

function create_slinks() {
    ln -s $SRC/sources/wkhtmltopdf-libs/lib/wkhtmltopdf/* $CPS/lib/wkhtmltopdf/
    ln -s $SRC/sources/wkhtmltopdf-libs/etc/tasks.d/task_reporting.py $CPS/etc/tasks.d/
    ln -s $SRC/sources/externals/webcore-libs $CPS/var/www/
    ln -s $SRC/sources/webcore/opt/webcore $CPS/opt/
    ln -s $SRC/sources/webcore/var/www/canopsis $CPS/var/www/
    ln -s $SRC/sources/collectd-libs/opt/collectd-libs $CPS/opt/
    ln -s $SRC/sources/mongodb-conf/opt/mongodb $CPS/opt/
    ln -s $SRC/sources/mongodb-conf/etc/schema.d $CPS/etc/
    # canolibs
    ln -sF $SRC/sources/python/cli/canopsis $CPS/lib/python2.7/site-packages/canopsis.cli-0.1-py2.7.egg/
    ln -s $SRC/sources/python/common/canopsis $CPS/lib/python2.7/site-packages/canopsis.common-0.1-py2.7.egg/
    ln -s $SRC/sources/python/configuration/canopsis $CPS/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/
    ln -s $SRC/sources/python/connectors/canopsis $CPS/lib/python2.7/site-packages/canopsis.connectors-0.1-py2.7.egg/
    ln -s $SRC/sources/python/connectors/var/snmp $CPS/var/
    ln -s $SRC/sources/python/context/canopsis $CPS/lib/python2.7/site-packages/canopsis.context-0.1-py2.7.egg/
    ln -s $SRC/sources/python/engines/canopsis $CPS/lib/python2.7/site-packages/canopsis.engines-0.1-py2.7.egg/
    ln -s $SRC/sources/python/mongo/canopsis $CPS/lib/python2.7/site-packages/canopsis.mongo-0.1-py2.7.egg/
    ln -s $SRC/sources/python/old/canopsis $CPS/lib/python2.7/site-packages/canopsis.old-0.1-py2.7.egg/
    ln -s $SRC/sources/python/organisation/canopsis $CPS/lib/python2.7/site-packages/canopsis.organisation-0.1-py2.7.egg/
    ln -s $SRC/sources/python/perfdata/canopsis $CPS/lib/python2.7/site-packages/canopsis.perfdata-0.1-py2.7.egg/
    ln -s $SRC/sources/python/storage/canopsis $CPS/lib/python2.7/site-packages/canopsis.storage-0.1-py2.7.egg/
    ln -s $SRC/sources/python/timeserie/canopsis $CPS/lib/python2.7/site-packages/canopsis.timeserie-0.1-py2.7.egg/
    ln -s $SRC/sources/python/tools/canopsis $CPS/lib/python2.7/site-packages/canopsis.tools-0.1-py2.7.egg/
    ln -s $SRC/sources/python/topology/canopsis $CPS/lib/python2.7/site-packages/canopsis.topology-0.1-py2.7.egg/
    ln -s $SRC/sources/python/auth/canopsis $CPS/lib/python2.7/site-packages/canopsis.auth-0.1-py2.7.egg/
    ln -s $SRC/sources/webcore/canopsis/webcore/services $CPS/lib/python2.7/site-packages/canopsis.webcore-0.8-py2.7.egg/canopsis/webcore/services
    touch $CPS/.slinked
}

function remove_slinks() {
    rm -Rf $CPS/opt/webcore
    rm -Rf $CPS/opt/collectd-libs
    rm -Rf $CPS/opt/mongodb
    rm -Rf $CPS/var/www/canopsis
    rm -Rf $CPS/var/www/webcore-libs
    rm -Rf $CPS/lib/wkhtmltopdf/*
    rm -Rf $CPS/etc/schema.d
    rm -Rf $CPS/etc/tasks.d/task_reporting.py
    # canolibs
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.cli-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.common-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.configuration-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.connectors-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/var/snmp
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.context-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.engines-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.mongo-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.old-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.organisation-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.perfdata-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.storage-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.timeserie-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.tools-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.topology-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.auth-0.1-py2.7.egg/canopsis
    rm -Rf $CPS/lib/python2.7/site-packages/canopsis.webcore-0.8-py2.7.egg/canopsis/webcore/services
    rm $CPS/.slinked 2>/dev/null
}
