- src: https://github.com/nginxinc/ansible-role-nginx
  scm: git

# adapted to our deployment needs
#- src: https://github.com/UnderGreen/ansible-role-mongodb
#  scm: git

# adapted to our deployment needs. Poorly maintained upstream
#- src: https://github.com/geerlingguy/ansible-role-rabbitmq
#  scm: git

- src: https://github.com/geerlingguy/ansible-role-redis
  scm: git

- src: https://gitlab.capensis.fr/projet-maat/ansible-role-repository-adder-maat
  scm: git
