// Code generated by MockGen. DO NOT EDIT.
// Source: git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/mongo (interfaces: CommandsRegister)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/lib/mongo/commands_register.go git.canopsis.net/canopsis/canopsis-community/community/go-engines-community/lib/mongo CommandsRegister
//

// Package mock_mongo is a generated GoMock package.
package mock_mongo

import (
	context "context"
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandsRegister is a mock of CommandsRegister interface.
type MockCommandsRegister struct {
	ctrl     *gomock.Controller
	recorder *MockCommandsRegisterMockRecorder
	isgomock struct{}
}

// MockCommandsRegisterMockRecorder is the mock recorder for MockCommandsRegister.
type MockCommandsRegisterMockRecorder struct {
	mock *MockCommandsRegister
}

// NewMockCommandsRegister creates a new mock instance.
func NewMockCommandsRegister(ctrl *gomock.Controller) *MockCommandsRegister {
	mock := &MockCommandsRegister{ctrl: ctrl}
	mock.recorder = &MockCommandsRegisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandsRegister) EXPECT() *MockCommandsRegisterMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockCommandsRegister) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockCommandsRegisterMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockCommandsRegister)(nil).Clear))
}

// Commit mocks base method.
func (m *MockCommandsRegister) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockCommandsRegisterMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockCommandsRegister)(nil).Commit), ctx)
}

// RegisterInsert mocks base method.
func (m *MockCommandsRegister) RegisterInsert(i any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterInsert", i)
}

// RegisterInsert indicates an expected call of RegisterInsert.
func (mr *MockCommandsRegisterMockRecorder) RegisterInsert(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterInsert", reflect.TypeOf((*MockCommandsRegister)(nil).RegisterInsert), i)
}

// RegisterUpdate mocks base method.
func (m *MockCommandsRegister) RegisterUpdate(id string, set bson.M) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterUpdate", id, set)
}

// RegisterUpdate indicates an expected call of RegisterUpdate.
func (mr *MockCommandsRegisterMockRecorder) RegisterUpdate(id, set any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUpdate", reflect.TypeOf((*MockCommandsRegister)(nil).RegisterUpdate), id, set)
}
