---
# DO NOT CHANGE
mongodb_version: '3.4'
mongodb_pymongo_from_pip: false
mongodb_security_authorization: enabled
# keep this variable empty for no replication and avoid canopsis role crash
mongodb_replication_replset:
influxdb_database_name: canopsis

# CHANGE ALLOWED
influxdb_username: canopsis
influxdb_password: canopsis
influxdb_ip_address: "127.0.0.1"
influxdb_http_interface: "0.0.0.0"
influxdb_admin_interface: "127.0.0.1"

mongodb_root_admin_name: root
mongodb_root_admin_password: root
mongodb_user_admin_name: admin
mongodb_user_admin_password: admin

# replication Options
#mongodb_replication_replset: <replset_name>

#canopsis_pkg_version: '2.5.15'
