#!/bin/sh
set -u

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
	echo "Usage: $0 start|status|restart|stop [systemd-service-pattern]"
	exit 1
fi

pattern="canopsis*"
if [ -n "${2:-}" ]; then
	pattern="$2"
fi

for service in $(systemctl list-units -a --type=service --plain --no-legend "$pattern" | awk '/^canopsis-/ {print $1}'); do
	systemctl --no-pager $1 "$service"
done
